Repository ChromeGaming/GameSphere, pull requests merged in 2023-07, with the labels that each got.

#667 Color_Crush_Game Added
  README.md
  SinglePlayer - Games/Banner - image/Color_Crush_Game.gif
  SinglePlayer - Games/Banner - image/Vedio_Game.gif
  SinglePlayer - Games/Color_Crush_Game/README.md
  SinglePlayer - Games/Color_Crush_Game/index.html
  SinglePlayer - Games/Color_Crush_Game/script.js
  SinglePlayer - Games/Color_Crush_Game/style.css
  SinglePlayer - Games/Vedio_Game/README.md
  SinglePlayer - Games/Vedio_Game/index.html
  SinglePlayer - Games/Vedio_Game/style.css
  SinglePlayer - Games/Vedio_Game/style.js
  additionalpage/game.html
Labels: gssoc23, level2

#682 Virtual Guitar
  README.md
  SinglePlayer - Games/Banner - image/VirtualGuitar.png
  SinglePlayer - Games/VirtualGuitar/app-orig.js
  SinglePlayer - Games/VirtualGuitar/app.js
  SinglePlayer - Games/VirtualGuitar/frets.html
  SinglePlayer - Games/VirtualGuitar/images/p.png
  SinglePlayer - Games/VirtualGuitar/index.html
  SinglePlayer - Games/VirtualGuitar/screen.png
  SinglePlayer - Games/VirtualGuitar/styles.css
  additionalpage/game.html
Labels: gssoc23, level1

#679 Added Ravoucs Raven RunGame 👾
  README.md
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/Bones.mp3
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/background.js
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/charlie-dont-surf-display-font.zip
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/charlie-dont-surf-display-font/charlie-dont-surf.otf
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/charlie-dont-surf-display-font/info.txt
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/collision.png
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/collisionanimation.js
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/enemies.js
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/enemy_bat_1.png
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/enemy_bat_2.png
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/enemy_bat_3.png
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/enemy_digger.png
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/enemy_fly.png
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/enemy_ghost_1.png
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/enemy_ghost_3.png
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/enemy_ghost_4.png
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/enemy_ground_zombie.png
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/enemy_hand.png
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/enemy_plant.png
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/enemy_raven.png
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/enemy_spider (1).png
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/enemy_spider_big - Copy.png
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/enemy_spider_big.png
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/enemy_spinner.png
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/enemy_worm (1).png
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/enemy_zombie.png
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/finalplayer.png
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/fire.png
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/index.html
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/input.js
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/layer-1.png
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/layer-2.png
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/layer-3.png
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/layer-4.png
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/layer-5.png
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/layer-6.2.png
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/layer-6.3.png
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/layer-6.png
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/layer01_Ground.1.png
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/main.js
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/particle.js
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/player.js
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/playerstate.js
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/style.css
  SinglePlayer - Games/Ravoucs_Raven_Run/FINAL/ui.js
  SinglePlayer - Games/Ravoucs_Raven_Run/README.md
  SinglePlayer - Games/Ravoucs_Raven_Run/Squiggly-Pattern.gif
  SinglePlayer - Games/Ravoucs_Raven_Run/hexwave.gif
  SinglePlayer - Games/Ravoucs_Raven_Run/index.html
  SinglePlayer - Games/Ravoucs_Raven_Run/modern-futuristic-sci-fi-background_35913-2150 (1).webp
  SinglePlayer - Games/Ravoucs_Raven_Run/particle.gif
  SinglePlayer - Games/Ravoucs_Raven_Run/script.js
  SinglePlayer - Games/Ravoucs_Raven_Run/style.css
  additionalpage/game.html
  assets/images/Ravoucs_Raven_Run.jpeg
Labels: gssoc23, level1

#694 game added
  SinglePlayer - Games/Egg_Catch_Game/Egg_Catch_Game.png
  SinglePlayer - Games/Egg_Catch_Game/README.md
  SinglePlayer - Games/Egg_Catch_Game/egg_catch.py
  additionalpage/game.html
Labels: gssoc23, level1

#684 Added Games News using `API`
  gamenews/script.js
  gamenews/style.css
  index.html
Labels: gssoc23, level1

#727 Added upgraded API
  gamenews/script.js
  gamenews/style.css
  index.html
Labels: gssoc23, level1

#723 Chinese_Checkers Added
  README.md
  SinglePlayer - Games/Banner - image/Chinese_Checkers.png
  SinglePlayer - Games/Chinese_Checkers/README.md
  SinglePlayer - Games/Chinese_Checkers/index.html
  SinglePlayer - Games/Chinese_Checkers/script.js
  SinglePlayer - Games/Chinese_Checkers/style.css
  additionalpage/game.html
Labels: gssoc23, level1

#735 ADDED CLASSIC GAME SNAKE
  ADDED CLASSIC GAME SNAKE
Labels: gssoc23, level1

#716 commit msg #654
  SinglePlayer - Games/Banner - image/cut_the_rope.png
  SinglePlayer - Games/cut_the_rope/css/style.css
  SinglePlayer - Games/cut_the_rope/img/background.jpg
  SinglePlayer - Games/cut_the_rope/img/candy.png
  SinglePlayer - Games/cut_the_rope/img/character.png
  SinglePlayer - Games/cut_the_rope/img/knife.png
  SinglePlayer - Games/cut_the_rope/index.html
  SinglePlayer - Games/cut_the_rope/js/script.js
  additional page/game.html
Labels: gssoc23, level1

#747 [GSSoC'23] Updating search & theme button
  additionalpage/game.html
  dist/color-theme.css
  style.css
Labels: gssoc23, level1

#749 Create lock.yml
  .github/workflows/lock.yml
Labels: gssoc23, level1

#752 New Game Add - PicPuzz
  README.md
  SinglePlayer - Games/Banner - image/PicPuzz-Complete the picture.jpg
  SinglePlayer - Games/PicPuzz/Assets1/1.jpg
  SinglePlayer - Games/PicPuzz/Assets1/2.jpg
  SinglePlayer - Games/PicPuzz/Assets1/3.jpg
  SinglePlayer - Games/PicPuzz/Assets1/4.jpg
  SinglePlayer - Games/PicPuzz/Assets1/5.jpg
  SinglePlayer - Games/PicPuzz/Assets1/6.jpg
  SinglePlayer - Games/PicPuzz/Assets1/7.jpg
  SinglePlayer - Games/PicPuzz/Assets1/8.jpg
  SinglePlayer - Games/PicPuzz/Assets1/9.jpg
  SinglePlayer - Games/PicPuzz/Assets1/blank.jpg
  SinglePlayer - Games/PicPuzz/Assets2/1.jpg
  SinglePlayer - Games/PicPuzz/Assets2/2.jpg
  SinglePlayer - Games/PicPuzz/Assets2/3.jpg
  SinglePlayer - Games/PicPuzz/Assets2/4.jpg
  SinglePlayer - Games/PicPuzz/Assets2/5.jpg
  SinglePlayer - Games/PicPuzz/Assets2/6.jpg
  SinglePlayer - Games/PicPuzz/Assets2/7.jpg
  SinglePlayer - Games/PicPuzz/Assets2/8.jpg
  SinglePlayer - Games/PicPuzz/Assets2/9.jpg
  SinglePlayer - Games/PicPuzz/Assets2/blank.jpg
  SinglePlayer - Games/PicPuzz/Assets3/1.jpg
  SinglePlayer - Games/PicPuzz/Assets3/2.jpg
  SinglePlayer - Games/PicPuzz/Assets3/3.jpg
  SinglePlayer - Games/PicPuzz/Assets3/4.jpg
  SinglePlayer - Games/PicPuzz/Assets3/5.jpg
  SinglePlayer - Games/PicPuzz/Assets3/6.jpg
  SinglePlayer - Games/PicPuzz/Assets3/7.jpg
  SinglePlayer - Games/PicPuzz/Assets3/8.jpg
  SinglePlayer - Games/PicPuzz/Assets3/9.jpg
  SinglePlayer - Games/PicPuzz/Assets3/blank.jpg
  SinglePlayer - Games/PicPuzz/PicPuzz-Complete the picture.jpg
  SinglePlayer - Games/PicPuzz/cross.png
  SinglePlayer - Games/PicPuzz/index.css
  SinglePlayer - Games/PicPuzz/index.html
  SinglePlayer - Games/PicPuzz/index.js
  SinglePlayer - Games/PicPuzz/puzz photo.jpg
  SinglePlayer - Games/PicPuzz/puzzle.css
  SinglePlayer - Games/PicPuzz/puzzle.html
  SinglePlayer - Games/PicPuzz/puzzle.js
  SinglePlayer - Games/PicPuzz/tick.png
  additionalpage/game.html
Labels: gssoc23, level1

#714 Highway race - Barrel Dodge GSSOC'23
  README.md
  SinglePlayer - Games/Banner - image/Highway_Race.png
  SinglePlayer - Games/Highway_Race/README.md
  SinglePlayer - Games/Highway_Race/Screenshots/Highway_Race.png
  SinglePlayer - Games/Highway_Race/barrel.png
  SinglePlayer - Games/Highway_Race/blue_car.png
  SinglePlayer - Games/Highway_Race/dur-icon2.png
  SinglePlayer - Games/Highway_Race/index.html
  SinglePlayer - Games/Highway_Race/road.png
  additionalpage/game.html
Labels: gssoc23, level1

#688 added Stacker game 👍
  README.md
  SinglePlayer - Games/Banner - image/Stacker.png
  SinglePlayer - Games/Stacker/README.md
  SinglePlayer - Games/Stacker/index.html
  SinglePlayer - Games/Stacker/script.js
  SinglePlayer - Games/Stacker/style.css
  additionalpage/game.html
Labels: gssoc23, level1

#768 Platform_Game_Engine Added
  README.md
  SinglePlayer - Games/Banner - image/Platform_Game_Engine.gif
  SinglePlayer - Games/Platform_Game_Engine/README.md
  SinglePlayer - Games/Platform_Game_Engine/index.html
  SinglePlayer - Games/Platform_Game_Engine/script.js
  SinglePlayer - Games/Platform_Game_Engine/style.css
  additionalpage/game.html
Labels: gssoc23, level2

#769 added Little Red - Riding Hood game 👍
  README.md
  SinglePlayer - Games/Banner - image/Little_Red.png
  SinglePlayer - Games/Little_Red/Little Red Riding Hood game.mp4
  SinglePlayer - Games/Little_Red/README.md
  SinglePlayer - Games/Little_Red/index.html
  SinglePlayer - Games/Little_Red/script.js
  SinglePlayer - Games/Little_Red/style.css
  additionalpage/game.html
Labels: gssoc23, level1

#775 Added aria attributes to contact us form
  additionalpage/contact.html
Labels: gssoc23, level1

#776 Castle_Escape_Game added
  README.md
  SinglePlayer - Games/Banner - image/Castle_Escape_Game.png
  SinglePlayer - Games/Castle_Escape_Game/data/convert.js
  SinglePlayer - Games/Castle_Escape_Game/data/map.json
  SinglePlayer - Games/Castle_Escape_Game/src/font.png
  SinglePlayer - Games/Castle_Escape_Game/src/index.html
  SinglePlayer - Games/Castle_Escape_Game/src/js/Item.js
  SinglePlayer - Games/Castle_Escape_Game/src/js/Player.js
  SinglePlayer - Games/Castle_Escape_Game/src/js/Room.js
  SinglePlayer - Games/Castle_Escape_Game/src/js/Sprite.js
  SinglePlayer - Games/Castle_Escape_Game/src/js/Tile.js
  SinglePlayer - Games/Castle_Escape_Game/src/js/World.js
  SinglePlayer - Games/Castle_Escape_Game/src/js/constants.js
  SinglePlayer - Games/Castle_Escape_Game/src/js/data.js
  SinglePlayer - Games/Castle_Escape_Game/src/js/debug.js
  SinglePlayer - Games/Castle_Escape_Game/src/js/font.js
  SinglePlayer - Games/Castle_Escape_Game/src/js/index.js
  SinglePlayer - Games/Castle_Escape_Game/src/js/input.js
  SinglePlayer - Games/Castle_Escape_Game/src/js/items/Chest.js
  SinglePlayer - Games/Castle_Escape_Game/src/js/items/Door.js
  SinglePlayer - Games/Castle_Escape_Game/src/js/items/Gate.js
  SinglePlayer - Games/Castle_Escape_Game/src/js/items/Key.js
  SinglePlayer - Games/Castle_Escape_Game/src/js/items/LavaBoots.js
  SinglePlayer - Games/Castle_Escape_Game/src/js/items/Lever.js
  SinglePlayer - Games/Castle_Escape_Game/src/js/items/MovingPlatform.js
  SinglePlayer - Games/Castle_Escape_Game/src/js/items/Note.js
  SinglePlayer - Games/Castle_Escape_Game/src/js/items/PopupPlatform.js
  SinglePlayer - Games/Castle_Escape_Game/src/js/items/Shears.js
  SinglePlayer - Games/Castle_Escape_Game/src/js/items/Spawn.js
  SinglePlayer - Games/Castle_Escape_Game/src/js/items/Spikes.js
  SinglePlayer - Games/Castle_Escape_Game/src/js/items/Thorns.js
  SinglePlayer - Games/Castle_Escape_Game/src/js/keyboard.js
  SinglePlayer - Games/Castle_Escape_Game/src/js/render.js
  SinglePlayer - Games/Castle_Escape_Game/src/js/rooms.js
  SinglePlayer - Games/Castle_Escape_Game/src/js/ui.js
  SinglePlayer - Games/Castle_Escape_Game/src/js/variables.js
  SinglePlayer - Games/Castle_Escape_Game/src/sprites.png
  SinglePlayer - Games/Castle_Escape_Game/src/style.css
  SinglePlayer - Games/Castle_Escape_Game/src/tiles.png
  additionalpage/game.html
Labels: gssoc23, level2

#788 Bejeweled
  README.md
  SinglePlayer - Games/Bejeweled/README.md
  SinglePlayer - Games/Bejeweled/assets/Bejeweled.mp4
  SinglePlayer - Games/Bejeweled/assets/Bejeweled.png
  SinglePlayer - Games/Bejeweled/css/game.css
  SinglePlayer - Games/Bejeweled/css/screen.css
  SinglePlayer - Games/Bejeweled/images/background_hover.png
  SinglePlayer - Games/Bejeweled/images/favicon.ico
  SinglePlayer - Games/Bejeweled/images/grid.png
  SinglePlayer - Games/Bejeweled/images/sprites/0.png
  SinglePlayer - Games/Bejeweled/images/sprites/0_explosion0.png
  SinglePlayer - Games/Bejeweled/images/sprites/0_explosion1.png
  SinglePlayer - Games/Bejeweled/images/sprites/1.png
  SinglePlayer - Games/Bejeweled/images/sprites/1_explosion0.png
  SinglePlayer - Games/Bejeweled/images/sprites/1_explosion1.png
  SinglePlayer - Games/Bejeweled/images/sprites/2.png
  SinglePlayer - Games/Bejeweled/images/sprites/2_explosion0.png
  SinglePlayer - Games/Bejeweled/images/sprites/2_explosion1.png
  SinglePlayer - Games/Bejeweled/images/sprites/3.png
  SinglePlayer - Games/Bejeweled/images/sprites/3_explosion0.png
  SinglePlayer - Games/Bejeweled/images/sprites/3_explosion1.png
  SinglePlayer - Games/Bejeweled/images/sprites/4.png
  SinglePlayer - Games/Bejeweled/images/sprites/4_explosion0.png
  SinglePlayer - Games/Bejeweled/images/sprites/4_explosion1.png
  SinglePlayer - Games/Bejeweled/images/sprites/5.png
  SinglePlayer - Games/Bejeweled/images/sprites/5_explosion0.png
  SinglePlayer - Games/Bejeweled/images/sprites/5_explosion1.png
  SinglePlayer - Games/Bejeweled/images/sprites/6.png
  SinglePlayer - Games/Bejeweled/images/sprites/6_explosion0.png
  SinglePlayer - Games/Bejeweled/images/sprites/6_explosion1.png
  SinglePlayer - Games/Bejeweled/images/sprites/7.png
  SinglePlayer - Games/Bejeweled/images/sprites/7_explosion0.png
  SinglePlayer - Games/Bejeweled/images/sprites/7_explosion1.png
  SinglePlayer - Games/Bejeweled/images/sprites/8.png
  SinglePlayer - Games/Bejeweled/images/sprites/8_explosion0.png
  SinglePlayer - Games/Bejeweled/images/sprites/8_explosion1.png
  SinglePlayer - Games/Bejeweled/images/sprites/9.png
  SinglePlayer - Games/Bejeweled/images/sprites/9_explosion0.png
  SinglePlayer - Games/Bejeweled/images/sprites/9_explosion1.png
  SinglePlayer - Games/Bejeweled/images/sprites/bomb.png
  SinglePlayer - Games/Bejeweled/images/sprites/gemSelected.gif
  SinglePlayer - Games/Bejeweled/images/sprites/h_arrow.png
  SinglePlayer - Games/Bejeweled/images/sprites/v_arrow.png
  SinglePlayer - Games/Bejeweled/index.html
  SinglePlayer - Games/Bejeweled/js/game/bonus.js
  SinglePlayer - Games/Bejeweled/js/game/capabilities/item.js
  SinglePlayer - Games/Bejeweled/js/game/classes/Bomb.js
  SinglePlayer - Games/Bejeweled/js/game/classes/Gem.js
  SinglePlayer - Games/Bejeweled/js/game/classes/Popup.js
  SinglePlayer - Games/Bejeweled/js/game/hint.js
  SinglePlayer - Games/Bejeweled/js/game/init.js
  SinglePlayer - Games/Bejeweled/js/game/level.js
  SinglePlayer - Games/Bejeweled/js/game/main.js
  SinglePlayer - Games/Bejeweled/js/game/score.js
  SinglePlayer - Games/Bejeweled/js/game/streak.js
  SinglePlayer - Games/Bejeweled/js/game/timer.js
  SinglePlayer - Games/Bejeweled/js/navigation.js
  SinglePlayer - Games/Bejeweled/js/util.js
  additionalpage/game.html
  assets/images/Bejeweled.png
Labels: gssoc23, level2

#789 new game added othello
  SinglePlayer - Games/Banner - image/othello.png
  SinglePlayer - Games/othello/README.md
  SinglePlayer - Games/othello/othello_ai.css
  SinglePlayer - Games/othello/othello_ai.html
  SinglePlayer - Games/othello/othello_ai.js
  additionalpage/game.html
Labels: gssoc23, level2

#770 Added a new game Stickman
  README.md
  SinglePlayer - Games/StickmanGame/.vscode/settings.json
  SinglePlayer - Games/StickmanGame/Sounds/Sword_sound.wav
  SinglePlayer - Games/StickmanGame/Sounds/jump_sound.wav
  SinglePlayer - Games/StickmanGame/Stickman Game.html
  SinglePlayer - Games/StickmanGame/block.js
  SinglePlayer - Games/StickmanGame/collision.js
  SinglePlayer - Games/StickmanGame/enemyMovement.js
  SinglePlayer - Games/StickmanGame/entity.js
  SinglePlayer - Games/StickmanGame/for vs eval.html
  SinglePlayer - Games/StickmanGame/graphics.js
  SinglePlayer - Games/StickmanGame/map creator.html
  SinglePlayer - Games/StickmanGame/movement.js
  SinglePlayer - Games/StickmanGame/string performance test.html
  SinglePlayer - Games/StickmanGame/util.js
  additionalpage/game.html
  assets/images/stickman.png
Labels: gssoc23, On Hold, level1

#756 Othello
  MultiPlayer - Games/Othello/index.html
  MultiPlayer - Games/Othello/script.js
  MultiPlayer - Games/Othello/style.css
  README.md
  SinglePlayer - Games/Banner - image/othello.PNG
Labels: gssoc23, level1, Paused

#792 Revert "new game added othello"
  SinglePlayer - Games/Banner - image/othello.png
  SinglePlayer - Games/othello/README.md
  SinglePlayer - Games/othello/othello_ai.css
  SinglePlayer - Games/othello/othello_ai.html
  SinglePlayer - Games/othello/othello_ai.js
  additionalpage/game.html
Labels: gssoc23, level3

#798 Shadow_Poke_Guessing_Game added
  README.md
  SinglePlayer - Games/Banner - image/Shadow_Poke_Guessing_Game.png
  SinglePlayer - Games/Shadow_Poke_Guessing_Game/M-logo.ico
  SinglePlayer - Games/Shadow_Poke_Guessing_Game/Pokemon Hollow.ttf
  SinglePlayer - Games/Shadow_Poke_Guessing_Game/Pokemon Solid.ttf
  SinglePlayer - Games/Shadow_Poke_Guessing_Game/README.md
  SinglePlayer - Games/Shadow_Poke_Guessing_Game/action.js
  SinglePlayer - Games/Shadow_Poke_Guessing_Game/background.jpg
  SinglePlayer - Games/Shadow_Poke_Guessing_Game/index.html
  SinglePlayer - Games/Shadow_Poke_Guessing_Game/style.css
  additionalpage/game.html
Labels: gssoc23, level2

#795 [GAME]: Magic-match
  README.md
  SinglePlayer - Games/Banner - image/Magic_match.png
  SinglePlayer - Games/Magic-match/README.md
  SinglePlayer - Games/Magic-match/magic-match-memory/.gitignore
  SinglePlayer - Games/Magic-match/magic-match-memory/package-lock.json
  SinglePlayer - Games/Magic-match/magic-match-memory/package.json
  SinglePlayer - Games/Magic-match/magic-match-memory/public/apple-touch-icon.png
  SinglePlayer - Games/Magic-match/magic-match-memory/public/favicon-16x16.png
  SinglePlayer - Games/Magic-match/magic-match-memory/public/favicon.ico
  SinglePlayer - Games/Magic-match/magic-match-memory/public/favicon.png
  SinglePlayer - Games/Magic-match/magic-match-memory/public/img/cover.png
  SinglePlayer - Games/Magic-match/magic-match-memory/public/img/helmet-1.png
  SinglePlayer - Games/Magic-match/magic-match-memory/public/img/potion-1.png
  SinglePlayer - Games/Magic-match/magic-match-memory/public/img/ring-1.png
  SinglePlayer - Games/Magic-match/magic-match-memory/public/img/scroll-1.png
  SinglePlayer - Games/Magic-match/magic-match-memory/public/img/shield-1.png
  SinglePlayer - Games/Magic-match/magic-match-memory/public/img/ss/img.png
  SinglePlayer - Games/Magic-match/magic-match-memory/public/img/ss/img1.png
  SinglePlayer - Games/Magic-match/magic-match-memory/public/img/sword-1.png
  SinglePlayer - Games/Magic-match/magic-match-memory/public/index.html
  SinglePlayer - Games/Magic-match/magic-match-memory/public/logo192.png
  SinglePlayer - Games/Magic-match/magic-match-memory/public/logo512.png
  SinglePlayer - Games/Magic-match/magic-match-memory/public/manifest.json
  SinglePlayer - Games/Magic-match/magic-match-memory/public/robots.txt
  SinglePlayer - Games/Magic-match/magic-match-memory/src/App.css
  SinglePlayer - Games/Magic-match/magic-match-memory/src/App.js
  SinglePlayer - Games/Magic-match/magic-match-memory/src/components/SingleCard.css
  SinglePlayer - Games/Magic-match/magic-match-memory/src/components/SingleCard.js
  SinglePlayer - Games/Magic-match/magic-match-memory/src/index.css
  SinglePlayer - Games/Magic-match/magic-match-memory/src/index.js
  additionalpage/game.html
  assets/images/Magic-Match.mp4
  assets/images/Magic_match.png
Labels: gssoc23, level2

#812 Digit Dilemma game added
  README.md
  SinglePlayer - Games/Banner - image/Digit_Dilemma.png
  SinglePlayer - Games/Digit_Dilemma/README.md
  SinglePlayer - Games/Digit_Dilemma/Screenshots/Digit_Dilemma.png
  SinglePlayer - Games/Digit_Dilemma/game.js
  SinglePlayer - Games/Digit_Dilemma/index.html
  SinglePlayer - Games/Digit_Dilemma/styles.css
  additionalpage/game.html
Labels: gssoc23, level1

#806 Animal_Name_Guessing_Game added
  README.md
  SinglePlayer - Games/Animal_Name_Guessing_Game/README.md
  SinglePlayer - Games/Animal_Name_Guessing_Game/css/styles.css
  SinglePlayer - Games/Animal_Name_Guessing_Game/game.html
  SinglePlayer - Games/Animal_Name_Guessing_Game/imgs/background.png
  SinglePlayer - Games/Animal_Name_Guessing_Game/index.html
  SinglePlayer - Games/Animal_Name_Guessing_Game/js/results.js
  SinglePlayer - Games/Animal_Name_Guessing_Game/js/script.js
  SinglePlayer - Games/Animal_Name_Guessing_Game/results.html
  SinglePlayer - Games/Banner - image/Animal Name_Guessing_Game.png
  additionalpage/game.html
Labels: gssoc23, level2

#814 Angry_Bird
  SinglePlayer - Games/Angry Birds/assets/bird1.svg
  SinglePlayer - Games/Angry Birds/assets/bird2.svg
  SinglePlayer - Games/Angry Birds/index.html
  SinglePlayer - Games/Angry Birds/main.js
  SinglePlayer - Games/Angry Birds/matter.js
  SinglePlayer - Games/Angry Birds/preview.png
  additionalpage/game.html
  assets/images/Angry_Birds.png
Labels: gssoc23, level1

#833 Marvel_Role_Playing_Game added
  README.md
  SinglePlayer - Games/Banner - image/Marvel_Role_Playing_Game.png
  SinglePlayer - Games/Marvel_Role_Player_Game/README.md
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/css/style.css
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/Ant_Man.png
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/Black_Panther.png
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/Captain_America.png
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/Iron_Man.png
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/avengers.jpg
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/slide-1.jpg
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/slide-10.jpeg
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/slide-11.jpg
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/slide-12.jpg
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/slide-13.jpg
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/slide-14.jpg
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/slide-15.jpg
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/slide-2.jpg
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/slide-3.jpg
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/slide-4.jpg
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/slide-5.jpg
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/slide-6.jpg
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/slide-7.jpg
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/slide-8.jpg
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/slide-9.jpg
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/javascript/game.js
  SinglePlayer - Games/Marvel_Role_Player_Game/index.html
  additionalpage/game.html
Labels: gssoc23, level2

#831 fixed the position of searchbar on multiplayer page
  additionalpage/multiplayer.html
  assets/images/guess-flag.png
  assets/images/ludo.png
Labels: gssoc23, level1

#837 Revert "Marvel_Role_Playing_Game added"
  README.md
  SinglePlayer - Games/Banner - image/Marvel_Role_Playing_Game.png
  SinglePlayer - Games/Marvel_Role_Player_Game/README.md
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/css/style.css
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/Ant_Man.png
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/Black_Panther.png
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/Captain_America.png
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/Iron_Man.png
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/avengers.jpg
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/slide-1.jpg
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/slide-10.jpeg
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/slide-11.jpg
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/slide-12.jpg
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/slide-13.jpg
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/slide-14.jpg
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/slide-15.jpg
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/slide-2.jpg
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/slide-3.jpg
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/slide-4.jpg
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/slide-5.jpg
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/slide-6.jpg
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/slide-7.jpg
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/slide-8.jpg
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/images/slide-9.jpg
  SinglePlayer - Games/Marvel_Role_Player_Game/assets/javascript/game.js
  SinglePlayer - Games/Marvel_Role_Player_Game/index.html
  additionalpage/game.html
Labels: gssoc23, level3

#838 Revert "Adding 2048 game"
  SinglePlayer - Games/2048game/2048.css
  SinglePlayer - Games/2048game/2048.js
  SinglePlayer - Games/2048game/Readme.md
  SinglePlayer - Games/2048game/index.html
  SinglePlayer - Games/Banner - image/2048.png
Labels: gssoc23, level3

#840 Basketball_Game Added
  README.md
  SinglePlayer - Games/Banner - image/Basketball Game.png
  SinglePlayer - Games/Basketball_Game/assets/audio/backboard.wav
  SinglePlayer - Games/Basketball_Game/assets/audio/fail.wav
  SinglePlayer - Games/Basketball_Game/assets/audio/score.wav
  SinglePlayer - Games/Basketball_Game/assets/audio/spawn.wav
  SinglePlayer - Games/Basketball_Game/assets/audio/whoosh.wav
  SinglePlayer - Games/Basketball_Game/assets/images/ball.png
  SinglePlayer - Games/Basketball_Game/assets/images/demo_pic.png
  SinglePlayer - Games/Basketball_Game/assets/images/front_rim.png
  SinglePlayer - Games/Basketball_Game/assets/images/hoop.png
  SinglePlayer - Games/Basketball_Game/assets/images/lose0.png
  SinglePlayer - Games/Basketball_Game/assets/images/lose1.png
  SinglePlayer - Games/Basketball_Game/assets/images/lose2.png
  SinglePlayer - Games/Basketball_Game/assets/images/lose3.png
  SinglePlayer - Games/Basketball_Game/assets/images/lose4.png
  SinglePlayer - Games/Basketball_Game/assets/images/side_rim.png
  SinglePlayer - Games/Basketball_Game/assets/images/win0.png
  SinglePlayer - Games/Basketball_Game/assets/images/win1.png
  SinglePlayer - Games/Basketball_Game/assets/images/win2.png
  SinglePlayer - Games/Basketball_Game/assets/images/win3.png
  SinglePlayer - Games/Basketball_Game/assets/images/win4.png
  SinglePlayer - Games/Basketball_Game/index.html
  SinglePlayer - Games/Basketball_Game/js/phaser.min.js
  additionalpage/game.html
Labels: gssoc23, level2

#839 Bug removed from the footer
  additionalpage/game.html
Labels: gssoc23, level1

#842 feat: newletter feature is added
  index.html
Labels: gssoc23, level2

#847 Math sprint game added
  README.md
  SinglePlayer - Games/Banner - image/Math_Sprint_Game.png
  SinglePlayer - Games/Math_Sprint_Game/README.md
  SinglePlayer - Games/Math_Sprint_Game/favicon.png
  SinglePlayer - Games/Math_Sprint_Game/index.html
  SinglePlayer - Games/Math_Sprint_Game/script.js
  SinglePlayer - Games/Math_Sprint_Game/shuffle.js
  SinglePlayer - Games/Math_Sprint_Game/style.css
  additionalpage/game.html
Labels: gssoc23, level2

#855 Ball_Jumper_Game added
  README.md
  SinglePlayer - Games/Ball_Jumper_Game/ParticleMesh.js
  SinglePlayer - Games/Ball_Jumper_Game/PlatformMesh.js
  SinglePlayer - Games/Ball_Jumper_Game/PlayerMesh.js
  SinglePlayer - Games/Ball_Jumper_Game/images/ballTexture.jpg
  SinglePlayer - Games/Ball_Jumper_Game/images/checkerboard.jpg
  SinglePlayer - Games/Ball_Jumper_Game/images/crate.jpg
  SinglePlayer - Games/Ball_Jumper_Game/images/flower.jpg
  SinglePlayer - Games/Ball_Jumper_Game/images/flower2.jpg
  SinglePlayer - Games/Ball_Jumper_Game/images/grass2.jpg
  SinglePlayer - Games/Ball_Jumper_Game/images/hedge.jpg
  SinglePlayer - Games/Ball_Jumper_Game/images/skybox/nx.jpg
  SinglePlayer - Games/Ball_Jumper_Game/images/skybox/ny.jpg
  SinglePlayer - Games/Ball_Jumper_Game/images/skybox/nz.jpg
  SinglePlayer - Games/Ball_Jumper_Game/images/skybox/px.jpg
  SinglePlayer - Games/Ball_Jumper_Game/images/skybox/py.jpg
  SinglePlayer - Games/Ball_Jumper_Game/images/skybox/pz.jpg
  SinglePlayer - Games/Ball_Jumper_Game/images/snow.png
  SinglePlayer - Games/Ball_Jumper_Game/js/Cache.js
  SinglePlayer - Games/Ball_Jumper_Game/js/CubeTextureLoader.js
  SinglePlayer - Games/Ball_Jumper_Game/js/ImageLoader.js
  SinglePlayer - Games/Ball_Jumper_Game/js/KeyboardState.js
  SinglePlayer - Games/Ball_Jumper_Game/js/MatrixStack.js
  SinglePlayer - Games/Ball_Jumper_Game/js/OBJLoader.js
  SinglePlayer - Games/Ball_Jumper_Game/js/OrbitControls.js
  SinglePlayer - Games/Ball_Jumper_Game/js/SourceLoader.js
  SinglePlayer - Games/Ball_Jumper_Game/js/Stats.js
  SinglePlayer - Games/Ball_Jumper_Game/js/banner.js
  SinglePlayer - Games/Ball_Jumper_Game/js/material.js
  SinglePlayer - Games/Ball_Jumper_Game/js/style.css
  SinglePlayer - Games/Ball_Jumper_Game/js/three.js
  SinglePlayer - Games/Ball_Jumper_Game/js/three.min.js
  SinglePlayer - Games/Ball_Jumper_Game/p4.html
  SinglePlayer - Games/Ball_Jumper_Game/p4.js
  SinglePlayer - Games/Ball_Jumper_Game/style.css
  SinglePlayer - Games/Banner - image/Ball_Jumper_Game .jpeg
  additionalpage/game.html
Labels: gssoc23, level2

#859 Added New Game Next Number in the sequence
  SinglePlayer - Games/Next-Number-In-The-Sequence/README.md
  SinglePlayer - Games/Next-Number-In-The-Sequence/index.html
  SinglePlayer - Games/Next-Number-In-The-Sequence/script.js
  SinglePlayer - Games/Next-Number-In-The-Sequence/styles.css
Labels: gssoc23, level1
