Repository ChromeGaming/GameSphere, pull requests merged in 2023-08, with the labels that each got.

#822 Updated contact form
  additionalpage/contact.html
Labels: invalid

#860 Simon_Game added
  README.md
  SinglePlayer - Games/Banner - image/Simon_Game.png
  SinglePlayer - Games/Simon_Game/index.html
  SinglePlayer - Games/Simon_Game/script.js
  SinglePlayer - Games/Simon_Game/style.css
  additionalpage/game.html
Labels: gssoc23, level1

#870 Revert "The Impossible Game "
  SinglePlayer - Games/Impossible Game/index.html
  SinglePlayer - Games/Impossible Game/script.js
  SinglePlayer - Games/Impossible Game/style.css
  additionalpage/game.html
  assets/images/impossible.png
Labels: gssoc23, level3

#871 Revert "Simon_Game added"
  README.md
  SinglePlayer - Games/Banner - image/Simon_Game.png
  SinglePlayer - Games/Simon_Game/index.html
  SinglePlayer - Games/Simon_Game/script.js
  SinglePlayer - Games/Simon_Game/style.css
  additionalpage/game.html
Labels: gssoc23, level3

#873 [GSSoC'23] Updating Readme file
  README.md
Labels: gssoc23, level1

#874 [GSSoC'23] Checkers Game Completed
  MultiPlayer - Games/Checkers-Game/angular.min.js
  MultiPlayer - Games/Checkers-Game/index.html
  MultiPlayer - Games/Checkers-Game/script.js
  MultiPlayer - Games/Checkers-Game/style.css
Labels: gssoc23, level1

#875 Bug removed
  additionalpage/game.html
Labels: gssoc23, level1

#884 [GSSoC'23] Added a preloader
  assets/images/preloader.gif
  index.html
  style.css
Labels: gssoc23, level2

#882 Game Connect Four
  MultiPlayer - Games/Connect_Four/Connect-Four.png
  MultiPlayer - Games/Connect_Four/README.md
  MultiPlayer - Games/Connect_Four/index.html
  MultiPlayer - Games/Connect_Four/script.js
  MultiPlayer - Games/Connect_Four/style.css
Labels: gssoc23, level1

#872 fix: Updated Multiple Issue Templates for GitHub Project Reposotories
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/styles.yml
Labels: gssoc23, level1

#891 Image Link Bug Removed
  additionalpage/game.html
Labels: gssoc23, level1

#896 Added Voice and txt assistant with FAQ AND NAVIGATION
  additionalpage/multiplayer.html
  index.html
  style.css
Labels: gssoc23, level2

#895 Removed repeated input fields of name and email
  additionalpage/contact.html
Labels: gssoc23, level1

#878 Game made the game
  README.md
  SinglePlayer - Games/Tenzies/.gitignore
  SinglePlayer - Games/Tenzies/.vscode/settings.json
  SinglePlayer - Games/Tenzies/README.md
  SinglePlayer - Games/Tenzies/package-lock.json
  SinglePlayer - Games/Tenzies/package.json
  SinglePlayer - Games/Tenzies/public/index.html
  SinglePlayer - Games/Tenzies/src/App.js
  SinglePlayer - Games/Tenzies/src/Die.js
  SinglePlayer - Games/Tenzies/src/index.js
  SinglePlayer - Games/Tenzies/src/style.css
Labels: gssoc23, level2

#900 [ADD]: FLIP THE CARD GAME
  SinglePlayer - Games/Banner - image/Flip_The_Card.png
  SinglePlayer - Games/Flip_The_Card/README.md
  SinglePlayer - Games/Flip_The_Card/index.html
  SinglePlayer - Games/Flip_The_Card/jQuery.js
  SinglePlayer - Games/Flip_The_Card/script.js
  SinglePlayer - Games/Flip_The_Card/style.css
Labels: gssoc23, level3

#898 Checkers Game Completed
  MultiPlayer - Games/Checkers-Game/angular.min.js
  MultiPlayer - Games/Checkers-Game/index.html
  MultiPlayer - Games/Checkers-Game/script.js
  MultiPlayer - Games/Checkers-Game/style.css
Labels: gssoc23, level3

#897 Game made the game
  README.md
  SinglePlayer - Games/Tenzies/.gitignore
  SinglePlayer - Games/Tenzies/.vscode/settings.json
  SinglePlayer - Games/Tenzies/README.md
  SinglePlayer - Games/Tenzies/package-lock.json
  SinglePlayer - Games/Tenzies/package.json
  SinglePlayer - Games/Tenzies/public/index.html
  SinglePlayer - Games/Tenzies/src/App.js
  SinglePlayer - Games/Tenzies/src/Die.js
  SinglePlayer - Games/Tenzies/src/index.js
  SinglePlayer - Games/Tenzies/src/style.css
Labels: gssoc23, level3

#909 feat: Added dynamic contributors section
  README.md
Labels: gssoc23, level1

#906 Dropkick Odyssey game added - GSSOC'23
  README.md
  SinglePlayer - Games/Banner - image/Dropkick_Odyssey.png
  SinglePlayer - Games/Dropkick_Odyssey/README.md
  SinglePlayer - Games/Dropkick_Odyssey/Screenshots/Dropkick_Odyssey.png
  SinglePlayer - Games/Dropkick_Odyssey/assets/css/reset.css
  SinglePlayer - Games/Dropkick_Odyssey/assets/css/style.css
  SinglePlayer - Games/Dropkick_Odyssey/assets/images/keyboard-key-arrow-up.svg
  SinglePlayer - Games/Dropkick_Odyssey/assets/images/keyboard-key-pointing-to-right.svg
  SinglePlayer - Games/Dropkick_Odyssey/assets/images/left-arrow-variant-key-on-keyboard.svg
  SinglePlayer - Games/Dropkick_Odyssey/index.html
  SinglePlayer - Games/Dropkick_Odyssey/javascript/Component.js
  SinglePlayer - Games/Dropkick_Odyssey/javascript/Enemy.js
  SinglePlayer - Games/Dropkick_Odyssey/javascript/Player.js
  SinglePlayer - Games/Dropkick_Odyssey/javascript/helperObj.js
  SinglePlayer - Games/Dropkick_Odyssey/javascript/main.js
  additionalpage/game.html
Labels: gssoc23, level1

#912 Dropkick Odyssey game
  README.md
  SinglePlayer - Games/Banner - image/Dropkick_Odyssey.png
  SinglePlayer - Games/Dropkick_Odyssey/README.md
  SinglePlayer - Games/Dropkick_Odyssey/Screenshots/Dropkick_Odyssey.png
  SinglePlayer - Games/Dropkick_Odyssey/assets/css/reset.css
  SinglePlayer - Games/Dropkick_Odyssey/assets/css/style.css
  SinglePlayer - Games/Dropkick_Odyssey/assets/images/keyboard-key-arrow-up.svg
  SinglePlayer - Games/Dropkick_Odyssey/assets/images/keyboard-key-pointing-to-right.svg
  SinglePlayer - Games/Dropkick_Odyssey/assets/images/left-arrow-variant-key-on-keyboard.svg
  SinglePlayer - Games/Dropkick_Odyssey/index.html
  SinglePlayer - Games/Dropkick_Odyssey/javascript/Component.js
  SinglePlayer - Games/Dropkick_Odyssey/javascript/Enemy.js
  SinglePlayer - Games/Dropkick_Odyssey/javascript/Player.js
  SinglePlayer - Games/Dropkick_Odyssey/javascript/helperObj.js
  SinglePlayer - Games/Dropkick_Odyssey/javascript/main.js
  additionalpage/game.html
Labels: gssoc23, level3
