Repository ChromeGaming/GameSphere, pull requests merged in 2023-06, with the labels that each got.

#186 💡 ADD: NEW GAME CALLED "FRANTIC RUN" (3D)
  SinglePlayer - Games/Frantic_Run/index.html
  SinglePlayer - Games/Frantic_Run/script.js
  SinglePlayer - Games/Frantic_Run/style.css
Labels: gssoc23, level2

#189 Minesweeper game added
  SinglePlayer - Games/Minesweeper Game/index.html
  SinglePlayer - Games/Minesweeper Game/script.js
  SinglePlayer - Games/Minesweeper Game/style.css
Labels: gssoc23, level2

#193 Added the Platform Game
  SinglePlayer - Games/Platform_Game/index.html
  SinglePlayer - Games/Platform_Game/script.js
  SinglePlayer - Games/Platform_Game/style.css
Labels: gssoc23, level2, 🎮 new game

#194 Added Tic_Tac_Toe game
  .vscode/settings.json
  MultiPlayer - Games/Tic_Tac_Toe/images/2078959.jpg
  MultiPlayer - Games/Tic_Tac_Toe/index.html
  MultiPlayer - Games/Tic_Tac_Toe/readme.md
  MultiPlayer - Games/Tic_Tac_Toe/script.js
  MultiPlayer - Games/Tic_Tac_Toe/style.css
Labels: gssoc23, level2

#208 [Enhancement]: Memory Card Game: After the game is over there comes no popup for play again or quit #156
  SinglePlayer - Games/Memory Game/index.html
  SinglePlayer - Games/Memory Game/script.js
  SinglePlayer - Games/Memory Game/style.css
Labels: gssoc23, level1

#182 Our stats added
  index.html
  style.css
Labels: gssoc23, level2

#215 Scrollbar styling changed
  dist/main.css
Labels: gssoc23, level1

#218 [ADD]: FLIP THE CARD GAME ✨
  SinglePlayer - Games/Banner - image/Flip_The_Card.png
  SinglePlayer - Games/Flip_The_Card/README.md
  SinglePlayer - Games/Flip_The_Card/index.html
  SinglePlayer - Games/Flip_The_Card/jQuery.js
  SinglePlayer - Games/Flip_The_Card/script.js
  SinglePlayer - Games/Flip_The_Card/style.css
Labels: gssoc23, level2

#219 [ADD]: PACIFIC AIR BATTLE GAME ✨
  SinglePlayer - Games/Banner - image/Pacific_Air_Battle.jpg
  SinglePlayer - Games/Pacific_Air_Battle/Framework.js
  SinglePlayer - Games/Pacific_Air_Battle/M4.js
  SinglePlayer - Games/Pacific_Air_Battle/README.md
  SinglePlayer - Games/Pacific_Air_Battle/WebGLUtils.js
  SinglePlayer - Games/Pacific_Air_Battle/ZzFXMicro.js
  SinglePlayer - Games/Pacific_Air_Battle/index.html
  SinglePlayer - Games/Pacific_Air_Battle/main.js
  SinglePlayer - Games/Pacific_Air_Battle/perlin.js
Labels: gssoc23, level2

#232 pinball game added
  SinglePlayer - Games/Banner - image/pinball.png
  SinglePlayer - Games/Pinball/images/sprites-min.png
  SinglePlayer - Games/Pinball/images/sprites.png
  SinglePlayer - Games/Pinball/images/sprites.xcf
  SinglePlayer - Games/Pinball/index.html
  SinglePlayer - Games/Pinball/js/controls.js
  SinglePlayer - Games/Pinball/js/game.js
  SinglePlayer - Games/Pinball/js/main.js
  SinglePlayer - Games/Pinball/js/renderer.js
  SinglePlayer - Games/Pinball/js/soundManager.js
  SinglePlayer - Games/Pinball/js/world.js
  SinglePlayer - Games/Pinball/tools/pinballEditor.html
Labels: gssoc23, level2

#223 chess added
  SinglePlayer - Games/Banner - image/chess.png
  SinglePlayer - Games/CHESS/Bbishop.png
  SinglePlayer - Games/CHESS/Bking.png
  SinglePlayer - Games/CHESS/Bknight.png
  SinglePlayer - Games/CHESS/Bpawn.png
  SinglePlayer - Games/CHESS/Bqueen.png
  SinglePlayer - Games/CHESS/Brook.png
  SinglePlayer - Games/CHESS/Chess.css
  SinglePlayer - Games/CHESS/Chess.js
  SinglePlayer - Games/CHESS/Wbishop.png
  SinglePlayer - Games/CHESS/Wking.png
  SinglePlayer - Games/CHESS/Wknight.png
  SinglePlayer - Games/CHESS/Wpawn.png
  SinglePlayer - Games/CHESS/Wqueen.png
  SinglePlayer - Games/CHESS/Wrook.png
  SinglePlayer - Games/CHESS/index.html
Labels: gssoc23, level2

#238 Additional pages- Games added #227
  SinglePlayer - Games/Banner - image/fall-down.png
  SinglePlayer - Games/Banner - image/minesweeper.png
  SinglePlayer - Games/Banner - image/platform-game.png
  SinglePlayer - Games/NecroticCommande/.husky/pre-commit
  SinglePlayer - Games/NecroticCommande/electron/electron.js
  SinglePlayer - Games/NecroticCommande/electron/electronBuild.bat
  SinglePlayer - Games/NecroticCommande/electron/electronSetup.bat
  SinglePlayer - Games/NecroticCommande/electron/package.json
  SinglePlayer - Games/NecroticCommande/engine/engine.all.js
  SinglePlayer - Games/NecroticCommande/engine/engine.all.min.js
  SinglePlayer - Games/NecroticCommande/engine/engine.all.release.js
  SinglePlayer - Games/NecroticCommande/engine/engine.js
  SinglePlayer - Games/NecroticCommande/engine/engineAudio.js
  SinglePlayer - Games/NecroticCommande/engine/engineBuild.bat
  SinglePlayer - Games/NecroticCommande/engine/engineDebug.js
  SinglePlayer - Games/NecroticCommande/engine/engineDraw.js
  SinglePlayer - Games/NecroticCommande/engine/engineFont.png
  SinglePlayer - Games/NecroticCommande/engine/engineInput.js
  SinglePlayer - Games/NecroticCommande/engine/engineMedals.js
  SinglePlayer - Games/NecroticCommande/engine/engineObject.js
  SinglePlayer - Games/NecroticCommande/engine/engineParticles.js
  SinglePlayer - Games/NecroticCommande/engine/engineRelease.js
  SinglePlayer - Games/NecroticCommande/engine/engineSettings.js
  SinglePlayer - Games/NecroticCommande/engine/engineTileLayer.js
  SinglePlayer - Games/NecroticCommande/engine/engineUtilities.js
  SinglePlayer - Games/NecroticCommande/engine/engineWebGL.js
  SinglePlayer - Games/NecroticCommande/engine/index.d.ts
  SinglePlayer - Games/NecroticCommande/favicon.png
  SinglePlayer - Games/NecroticCommande/game.js
  SinglePlayer - Games/NecroticCommande/index.html
  SinglePlayer - Games/NecroticCommande/package-lock.json
  SinglePlayer - Games/NecroticCommande/package.json
  SinglePlayer - Games/NecroticCommande/tiles.png
  SinglePlayer - Games/js13k-death/.jshintrc
  SinglePlayer - Games/js13k-death/LittleJS-build.sh
  SinglePlayer - Games/js13k-death/build.sh
  SinglePlayer - Games/js13k-death/dev/index-dev.html
  SinglePlayer - Games/js13k-death/dev/js/Creature.js
  SinglePlayer - Games/js13k-death/dev/js/Level.js
  SinglePlayer - Games/js13k-death/dev/js/Player.js
  SinglePlayer - Games/js13k-death/dev/js/Tile.js
  SinglePlayer - Games/js13k-death/dev/js/TurnManager.js
  SinglePlayer - Games/js13k-death/dev/js/UI.js
  SinglePlayer - Games/js13k-death/dev/js/js13k.js
  SinglePlayer - Games/js13k-death/dev/js/littlejs.custom.js
  SinglePlayer - Games/js13k-death/dev/tiles.aseprite
  SinglePlayer - Games/js13k-death/dev/tiles.png
  SinglePlayer - Games/js13k-death/docs/i.js
  SinglePlayer - Games/js13k-death/docs/index.html
  SinglePlayer - Games/js13k-death/docs/tiles.png
  SinglePlayer - Games/js13k-death/thumb_160x160.png
  SinglePlayer - Games/js13k-death/thumb_400x250.png
  additional page/game.html
Labels: gssoc23, level2

#239 copy right footer added
  index.html
  style.css
Labels: gssoc23, level1

#244 [ADD]: TRACK NOT FOUND GAME 👾
  SinglePlayer - Games/Banner - image/Track_Not_Found.jpg
  SinglePlayer - Games/Track_Not_Found/1f441.svg
  SinglePlayer - Games/Track_Not_Found/1f4a5.svg
  SinglePlayer - Games/Track_Not_Found/1f4f7.svg
  SinglePlayer - Games/Track_Not_Found/1f682.svg
  SinglePlayer - Games/Track_Not_Found/1f9e8.svg
  SinglePlayer - Games/Track_Not_Found/README.md
  SinglePlayer - Games/Track_Not_Found/fs.svg
  SinglePlayer - Games/Track_Not_Found/index.html
Labels: gssoc23, level2

#226 Card flip Game
  SinglePlayer - Games/Card flip Game/dog.png
  SinglePlayer - Games/Card flip Game/doll.png
  SinglePlayer - Games/Card flip Game/duck.png
  SinglePlayer - Games/Card flip Game/fish-color.png
  SinglePlayer - Games/Card flip Game/flames.png
  SinglePlayer - Games/Card flip Game/index.html
  SinglePlayer - Games/Card flip Game/logic.js
  SinglePlayer - Games/Card flip Game/pork.png
  SinglePlayer - Games/Card flip Game/readme
  SinglePlayer - Games/Card flip Game/style.css
  SinglePlayer - Games/Card flip Game/teddy-bear-brown.png
  SinglePlayer - Games/Card flip Game/traffic-light.png
Labels: gssoc23, level2

#249 Pull Request Template Added
  .github/Pull_Request_Template.md
Labels: gssoc23, level1

#246 Added slide puzzle game
  SinglePlayer - Games/Banner - image/slide_puzzle.png
  SinglePlayer - Games/slide-puzzle-master/1.jpg
  SinglePlayer - Games/slide-puzzle-master/10.jpg
  SinglePlayer - Games/slide-puzzle-master/2.jpg
  SinglePlayer - Games/slide-puzzle-master/3.jpg
  SinglePlayer - Games/slide-puzzle-master/4.jpg
  SinglePlayer - Games/slide-puzzle-master/5.jpg
  SinglePlayer - Games/slide-puzzle-master/5x5 puzzle challenge/1.jpg
  SinglePlayer - Games/slide-puzzle-master/5x5 puzzle challenge/10.jpg
  SinglePlayer - Games/slide-puzzle-master/5x5 puzzle challenge/11.jpg
  SinglePlayer - Games/slide-puzzle-master/5x5 puzzle challenge/12.jpg
  SinglePlayer - Games/slide-puzzle-master/5x5 puzzle challenge/13.jpg
  SinglePlayer - Games/slide-puzzle-master/5x5 puzzle challenge/14.jpg
  SinglePlayer - Games/slide-puzzle-master/5x5 puzzle challenge/15.jpg
  SinglePlayer - Games/slide-puzzle-master/5x5 puzzle challenge/16.jpg
  SinglePlayer - Games/slide-puzzle-master/5x5 puzzle challenge/17.jpg
  SinglePlayer - Games/slide-puzzle-master/5x5 puzzle challenge/18.jpg
  SinglePlayer - Games/slide-puzzle-master/5x5 puzzle challenge/19.jpg
  SinglePlayer - Games/slide-puzzle-master/5x5 puzzle challenge/2.jpg
  SinglePlayer - Games/slide-puzzle-master/5x5 puzzle challenge/20.jpg
  SinglePlayer - Games/slide-puzzle-master/5x5 puzzle challenge/21.jpg
  SinglePlayer - Games/slide-puzzle-master/5x5 puzzle challenge/22.jpg
  SinglePlayer - Games/slide-puzzle-master/5x5 puzzle challenge/23.jpg
  SinglePlayer - Games/slide-puzzle-master/5x5 puzzle challenge/24.jpg
  SinglePlayer - Games/slide-puzzle-master/5x5 puzzle challenge/25.jpg
  SinglePlayer - Games/slide-puzzle-master/5x5 puzzle challenge/26.jpg
  SinglePlayer - Games/slide-puzzle-master/5x5 puzzle challenge/3.jpg
  SinglePlayer - Games/slide-puzzle-master/5x5 puzzle challenge/4.jpg
  SinglePlayer - Games/slide-puzzle-master/5x5 puzzle challenge/5.jpg
  SinglePlayer - Games/slide-puzzle-master/5x5 puzzle challenge/5_.jpg
  SinglePlayer - Games/slide-puzzle-master/5x5 puzzle challenge/6.jpg
  SinglePlayer - Games/slide-puzzle-master/5x5 puzzle challenge/7.jpg
  SinglePlayer - Games/slide-puzzle-master/5x5 puzzle challenge/8.jpg
  SinglePlayer - Games/slide-puzzle-master/5x5 puzzle challenge/9.jpg
  SinglePlayer - Games/slide-puzzle-master/6.jpg
  SinglePlayer - Games/slide-puzzle-master/7.jpg
  SinglePlayer - Games/slide-puzzle-master/8.jpg
  SinglePlayer - Games/slide-puzzle-master/9.jpg
  SinglePlayer - Games/slide-puzzle-master/README.md
  SinglePlayer - Games/slide-puzzle-master/index.html
  SinglePlayer - Games/slide-puzzle-master/logo.png
  SinglePlayer - Games/slide-puzzle-master/output_screenshot
  SinglePlayer - Games/slide-puzzle-master/puzzle.css
  SinglePlayer - Games/slide-puzzle-master/puzzle.js
Labels: gssoc23, level2

#257 [GSSoC'23] Added connect4, issue #255
  SinglePlayer - Games/Banner - image/Connect4.png
  SinglePlayer - Games/Connect4/connect4.css
  SinglePlayer - Games/Connect4/connect4.js
  SinglePlayer - Games/Connect4/game.html
  SinglePlayer - Games/Connect4/index.html
Labels: gssoc23, level2

#267 [GSSoC'23] Music guess game Completed !
  MultiPlayer - Games/Music Guess Game/images/Music_Guess_Game.png
  MultiPlayer - Games/Music Guess Game/images/Music_Guess_Game1.png
  MultiPlayer - Games/Music Guess Game/images/PlayingCaste.gif
  MultiPlayer - Games/Music Guess Game/index.html
  MultiPlayer - Games/Music Guess Game/script.js
  MultiPlayer - Games/Music Guess Game/songs/Aafat - Liger.mp3
  MultiPlayer - Games/Music Guess Game/songs/Aapke Pyaar Mein Hum.mp3
  MultiPlayer - Games/Music Guess Game/songs/Apna Bna Le.mp3
  MultiPlayer - Games/Music Guess Game/songs/Apni Toh Jaise Taise.mp3
  MultiPlayer - Games/Music Guess Game/songs/Ban Meri Rani.mp3
  MultiPlayer - Games/Music Guess Game/songs/Bholi Si Surat.mp3
  MultiPlayer - Games/Music Guess Game/songs/Chand Chuppa.mp3
  MultiPlayer - Games/Music Guess Game/songs/Chorbazari.mp3
  MultiPlayer - Games/Music Guess Game/songs/Chupke Chupke.mp3
  MultiPlayer - Games/Music Guess Game/songs/Current Laga Re.mp3
  MultiPlayer - Games/Music Guess Game/songs/Daru Badnam.mp3
  MultiPlayer - Games/Music Guess Game/songs/Girl I Need You.mp3
  MultiPlayer - Games/Music Guess Game/songs/Jeda Nasha Nasha.mp3
  MultiPlayer - Games/Music Guess Game/songs/Jhoome Jo Pathan.mp3
  MultiPlayer - Games/Music Guess Game/songs/Kaun Tujhe.mp3
  MultiPlayer - Games/Music Guess Game/songs/Kitna Haseen Chehra.mp3
  MultiPlayer - Games/Music Guess Game/songs/Maarkhayega.mp3
  MultiPlayer - Games/Music Guess Game/songs/Mast Nazron Se Allah Bachaye.mp3
  MultiPlayer - Games/Music Guess Game/songs/Nacho Nacho.mp3
  MultiPlayer - Games/Music Guess Game/songs/Neele Neele Amber.mp3
  MultiPlayer - Games/Music Guess Game/songs/O Saki Saki.mp3
  MultiPlayer - Games/Music Guess Game/songs/Om Deva Deva.mp3
  MultiPlayer - Games/Music Guess Game/songs/Ramaiya Vastavaiya.mp3
  MultiPlayer - Games/Music Guess Game/songs/Thumkeswari.mp3
  MultiPlayer - Games/Music Guess Game/songs/Tujh Me Rab Dikhta.mp3
  MultiPlayer - Games/Music Guess Game/songs/Zara Tasveer Se Tu.mp3
  MultiPlayer - Games/Music Guess Game/sounds/gameOver.mp3
  MultiPlayer - Games/Music Guess Game/sounds/playAgain.mp3
  MultiPlayer - Games/Music Guess Game/sounds/rightAnswer.mp3
  MultiPlayer - Games/Music Guess Game/sounds/wrongAnswer.mp3
  MultiPlayer - Games/Music Guess Game/style.css
Labels: gssoc23, level2

#265 Created A New Game Snakes And Ladders
  SinglePlayer - Games/Candy_Crush/Music.mp3
  SinglePlayer - Games/Candy_Crush/Swap.mp3
  SinglePlayer - Games/Candy_Crush/index.html
  SinglePlayer - Games/Candy_Crush/script.js
  SinglePlayer - Games/Snakes And Ladders
  SinglePlayer - Games/snakes and ladder/Assets/Dice Roll.mp3
  SinglePlayer - Games/snakes and ladder/Assets/background.jpg
  SinglePlayer - Games/snakes and ladder/Assets/ladder.mp3
  SinglePlayer - Games/snakes and ladder/Assets/snake.mp3
  SinglePlayer - Games/snakes and ladder/Assets/snl.jpg
  SinglePlayer - Games/snakes and ladder/Assets/snlMusic.mp3
  SinglePlayer - Games/snakes and ladder/index.html
  SinglePlayer - Games/snakes and ladder/script.js
  SinglePlayer - Games/snakes and ladder/style.css
Labels: gssoc23, level2

#270 Added Whack-a-mole Game
  SinglePlayer - Games/whack-a-mole/background.jpg
  SinglePlayer - Games/whack-a-mole/index.html
  SinglePlayer - Games/whack-a-mole/mole-image.jpg
  SinglePlayer - Games/whack-a-mole/pngtree-mole-image.jpg
  SinglePlayer - Games/whack-a-mole/script.js
  SinglePlayer - Games/whack-a-mole/style.css
  SinglePlayer - Games/whack-a-mole/whack-a-mole.png
  additional page/game.html
Labels: gssoc23, level2

#272 First: Guess The Number
  SinglePlayer - Games/Guess The Number/README.md
  SinglePlayer - Games/Guess The Number/assets/Background.jpg
  SinglePlayer - Games/Guess The Number/assets/card-img.jpg
  SinglePlayer - Games/Guess The Number/assets/card..png
  SinglePlayer - Games/Guess The Number/index.html
  SinglePlayer - Games/Guess The Number/main.js
  SinglePlayer - Games/Guess The Number/style.css
  additional page/game.html
Labels: gssoc23, level2

#274 Added Bouncing ball animation
  index.html
  style.css
Labels: gssoc23, level2

#275 Added code pong game
  SinglePlayer - Games/Banner - image/code pong.png
  SinglePlayer - Games/Code Pong game/index.html
  SinglePlayer - Games/Code Pong game/script.js
Labels: gssoc23, level2

#276 Added space invaders
  SinglePlayer - Games/Banner - image/Space inavders.png
  SinglePlayer - Games/space-invaders/space-invaders-master/alien-cyan.png
  SinglePlayer - Games/space-invaders/space-invaders-master/alien-magenta.png
  SinglePlayer - Games/space-invaders/space-invaders-master/alien-yellow.png
  SinglePlayer - Games/space-invaders/space-invaders-master/alien.png
  SinglePlayer - Games/space-invaders/space-invaders-master/index.html
  SinglePlayer - Games/space-invaders/space-invaders-master/ship.png
  SinglePlayer - Games/space-invaders/space-invaders-master/space.css
  SinglePlayer - Games/space-invaders/space-invaders-master/space.js
Labels: gssoc23, level2

#289 Added New Game SUDOKU
  SinglePlayer - Games/SUDOKU/app.py
  SinglePlayer - Games/SUDOKU/generator.py
  SinglePlayer - Games/SUDOKU/index.html
  SinglePlayer - Games/SUDOKU/play-again-logo.jpg
  SinglePlayer - Games/SUDOKU/sudoku.css
  SinglePlayer - Games/SUDOKU/sudoku.js
  SinglePlayer - Games/SUDOKU/sudoku_gen_solve.js
Labels: gssoc23, level2, Change request

#295 [ADD]: GALAXY RIDER GAME 👾
  SinglePlayer - Games/Banner - image/Galaxy_Rider.jpg
  SinglePlayer - Games/Galaxy_Rider/README.md
  SinglePlayer - Games/Galaxy_Rider/index.html
Labels: gssoc23, level2

#296 Added typing game
  SinglePlayer - Games/Banner - image/SpotifySetup.exe
  SinglePlayer - Games/Typing Game/README.md
  SinglePlayer - Games/Typing Game/index.html
  SinglePlayer - Games/Typing Game/script.js
  SinglePlayer - Games/Typing Game/style.css
Labels: gssoc23, level2

#298 Theme issue solved
  additionalpage/contact.html
  additionalpage/game.html
  additionalpage/multiplayer.html
  index.html
  style.css
Labels: gssoc23, level1

#303 Added hover effect on cards
  dist/main.css
Labels: gssoc23, level2

#301 Added Dinosaur Game files
  SinglePlayer - Games/Banner - image/Dinosaur_Game.png
  SinglePlayer - Games/Dinosaur_Game/Assets/Bird/Bird1.png
  SinglePlayer - Games/Dinosaur_Game/Assets/Bird/Bird2.png
  SinglePlayer - Games/Dinosaur_Game/Assets/Cactus/LargeCactus1.png
  SinglePlayer - Games/Dinosaur_Game/Assets/Cactus/LargeCactus2.png
  SinglePlayer - Games/Dinosaur_Game/Assets/Cactus/LargeCactus3.png
  SinglePlayer - Games/Dinosaur_Game/Assets/Cactus/SmallCactus1.png
  SinglePlayer - Games/Dinosaur_Game/Assets/Cactus/SmallCactus2.png
  SinglePlayer - Games/Dinosaur_Game/Assets/Cactus/SmallCactus3.png
  SinglePlayer - Games/Dinosaur_Game/Assets/Dino/DinoDuck1.png
  SinglePlayer - Games/Dinosaur_Game/Assets/Dino/DinoDuck2.png
  SinglePlayer - Games/Dinosaur_Game/Assets/Dino/DinoJump.png
  SinglePlayer - Games/Dinosaur_Game/Assets/Dino/DinoRun1.png
  SinglePlayer - Games/Dinosaur_Game/Assets/Dino/DinoRun2.png
  SinglePlayer - Games/Dinosaur_Game/Assets/Dino/DinoStart.png
  SinglePlayer - Games/Dinosaur_Game/Assets/Other/Cloud.png
  SinglePlayer - Games/Dinosaur_Game/Assets/Other/Track.png
  SinglePlayer - Games/Dinosaur_Game/README.md
  SinglePlayer - Games/Dinosaur_Game/dino.gif
  SinglePlayer - Games/Dinosaur_Game/main.py
Labels: gssoc23, level2

#291 commit msg #279
  SinglePlayer - Games/Banner - image/alien-shooting-game.png
  SinglePlayer - Games/alien-shooting-game/alien.png
  SinglePlayer - Games/alien-shooting-game/app.js
  SinglePlayer - Games/alien-shooting-game/bullet.png
  SinglePlayer - Games/alien-shooting-game/index.html
  SinglePlayer - Games/alien-shooting-game/rocket.png
  SinglePlayer - Games/alien-shooting-game/space.jpg
Labels: gssoc23, level2

#306 [ADD]: BACK TO SPACE GAME 👾
  SinglePlayer - Games/Back_To_Space/README.md
  SinglePlayer - Games/Back_To_Space/index.html
  SinglePlayer - Games/Banner - image/Back_To_Space.jpg
Labels: gssoc23, level2

#315 4 player Ludo game
  MultiPlayer - Games/Ludo_4_Player/README.md
  MultiPlayer - Games/Ludo_4_Player/assets/images/crown1.png
  MultiPlayer - Games/Ludo_4_Player/assets/images/crown2.png
  MultiPlayer - Games/Ludo_4_Player/assets/images/crown3.png
  MultiPlayer - Games/Ludo_4_Player/assets/images/dice_1.png
  MultiPlayer - Games/Ludo_4_Player/assets/sounds/dice.mp3
  MultiPlayer - Games/Ludo_4_Player/assets/sounds/inout.mp3
  MultiPlayer - Games/Ludo_4_Player/assets/sounds/killed.mp3
  MultiPlayer - Games/Ludo_4_Player/assets/sounds/step.mp3
  MultiPlayer - Games/Ludo_4_Player/assets/sounds/win.mp3
  MultiPlayer - Games/Ludo_4_Player/index.html
  MultiPlayer - Games/Ludo_4_Player/script.js
  MultiPlayer - Games/Ludo_4_Player/style.css
Labels: gssoc23, level2

#309 Added Whake A Mole Game
  SinglePlayer - Games/Banner - image/Whake_A_Mole_Game.png
  SinglePlayer - Games/Whake_M_Mole_Game/images/mario-bg.jpg
  SinglePlayer - Games/Whake_M_Mole_Game/images/monty-mole.png
  SinglePlayer - Games/Whake_M_Mole_Game/images/pipe.png
  SinglePlayer - Games/Whake_M_Mole_Game/images/piranha-plant.png
  SinglePlayer - Games/Whake_M_Mole_Game/images/soil.png
  SinglePlayer - Games/Whake_M_Mole_Game/index.html
  SinglePlayer - Games/Whake_M_Mole_Game/mole.css
  SinglePlayer - Games/Whake_M_Mole_Game/mole.js
Labels: gssoc23, level2

#317 Added Drum_Play_Game (GSSOC '23)(Issue: #273)
  SinglePlayer - Games/Banner - image/screenshot_drum_play.png
  SinglePlayer - Games/Drum_Kit_Play_Game/README.md
  SinglePlayer - Games/Drum_Kit_Play_Game/images/crash.png
  SinglePlayer - Games/Drum_Kit_Play_Game/images/kick.png
  SinglePlayer - Games/Drum_Kit_Play_Game/images/snare.png
  SinglePlayer - Games/Drum_Kit_Play_Game/images/tom1.png
  SinglePlayer - Games/Drum_Kit_Play_Game/images/tom2.png
  SinglePlayer - Games/Drum_Kit_Play_Game/images/tom3.png
  SinglePlayer - Games/Drum_Kit_Play_Game/images/tom4.png
  SinglePlayer - Games/Drum_Kit_Play_Game/index.html
  SinglePlayer - Games/Drum_Kit_Play_Game/index.js
  SinglePlayer - Games/Drum_Kit_Play_Game/sounds/crash.mp3
  SinglePlayer - Games/Drum_Kit_Play_Game/sounds/kick-bass.mp3
  SinglePlayer - Games/Drum_Kit_Play_Game/sounds/snare.mp3
  SinglePlayer - Games/Drum_Kit_Play_Game/sounds/tom-1.mp3
  SinglePlayer - Games/Drum_Kit_Play_Game/sounds/tom-2.mp3
  SinglePlayer - Games/Drum_Kit_Play_Game/sounds/tom-3.mp3
  SinglePlayer - Games/Drum_Kit_Play_Game/sounds/tom-4.mp3
  SinglePlayer - Games/Drum_Kit_Play_Game/styles.css
Labels: gssoc23, level2

#332 Added Rubick's cube game
  SinglePlayer - Games/Rubik_Cube/index.html
  SinglePlayer - Games/Rubik_Cube/rubik.png
  SinglePlayer - Games/Rubik_Cube/script.js
  SinglePlayer - Games/Rubik_Cube/style.css
  additionalpage/game.html
Labels: gssoc23

#337 Fixed navbar bug on all pages
  SinglePlayer - Games/Banner - image/rubik.png
  additionalpage/contact.html
  additionalpage/game.html
  additionalpage/multiplayer.html
  index.html
Labels: gssoc23

#338 commit msg #305
  SinglePlayer - Games/Banner - image/doodle-jump-game.png
  SinglePlayer - Games/doodle-jump-game/doodlejumpbg.png
  SinglePlayer - Games/doodle-jump-game/doodler-left.png
  SinglePlayer - Games/doodle-jump-game/doodler-right.png
  SinglePlayer - Games/doodle-jump-game/index.html
  SinglePlayer - Games/doodle-jump-game/index.js
  SinglePlayer - Games/doodle-jump-game/platform-broken.png
  SinglePlayer - Games/doodle-jump-game/platform.png
  SinglePlayer - Games/doodle-jump-game/styles.css
Labels: gssoc23, level2

#358 Meta tags added
  index.html
Labels: gssoc23, level1

#356 Bullseye Game is added
  .vscode/settings.json
  SinglePlayer - Games/BullseyeGame/image.png
  SinglePlayer - Games/BullseyeGame/index.html
  SinglePlayer - Games/BullseyeGame/script.js
  SinglePlayer - Games/BullseyeGame/style.css
  additionalpage/game.html
Labels: gssoc23, level2

#354 Added the game of Box Slice🚩
  SinglePlayer - Games/Banner - image/box_slice.png
  SinglePlayer - Games/Box_Slice/README.md
  SinglePlayer - Games/Box_Slice/index.html
  SinglePlayer - Games/Box_Slice/script.js
  SinglePlayer - Games/Box_Slice/style.css
  additionalpage/game.html
Labels: gssoc23, level2

#369 Added Doremon Puzzle Game
  SinglePlayer - Games/Banner - image/Doremon_Puzzle.png
  SinglePlayer - Games/Doremon_Puzzle/1.jpg
  SinglePlayer - Games/Doremon_Puzzle/10.jpg
  SinglePlayer - Games/Doremon_Puzzle/2.jpg
  SinglePlayer - Games/Doremon_Puzzle/3.jpg
  SinglePlayer - Games/Doremon_Puzzle/4.jpg
  SinglePlayer - Games/Doremon_Puzzle/5.jpg
  SinglePlayer - Games/Doremon_Puzzle/6.jpg
  SinglePlayer - Games/Doremon_Puzzle/7.jpg
  SinglePlayer - Games/Doremon_Puzzle/8.jpg
  SinglePlayer - Games/Doremon_Puzzle/9.jpg
  SinglePlayer - Games/Doremon_Puzzle/index.html
  SinglePlayer - Games/Doremon_Puzzle/logo.png
  SinglePlayer - Games/Doremon_Puzzle/puzzle.css
  SinglePlayer - Games/Doremon_Puzzle/puzzle.js
  additionalpage/game.html
Labels: gssoc23, level2

#367 Dragon World game Added
  SinglePlayer - Games/Banner - image/Dragon_World_game.png
  SinglePlayer - Games/Dragon_World_Game/README.md
  SinglePlayer - Games/Dragon_World_Game/images/cover.png
  SinglePlayer - Games/Dragon_World_Game/images/dragon.png
  SinglePlayer - Games/Dragon_World_Game/images/obstacle.png
  SinglePlayer - Games/Dragon_World_Game/index.html
  SinglePlayer - Games/Dragon_World_Game/style.css
Labels: gssoc23, level2

#342 Snake Game
  SinglePlayer - Games/Snake Game/snake.png
  SinglePlayer - Games/Snake Game/snake.py
  additionalpage/game.html
Labels: gssoc23, level2

#366 Stack 3D Game ⚡
  SinglePlayer - Games/Banner - image/Stack-Game-main.png
  SinglePlayer - Games/Stack-Game-main/Stack-Game-main/index.html
  SinglePlayer - Games/Stack-Game-main/Stack-Game-main/main.js
  SinglePlayer - Games/Stack-Game-main/Stack-Game-main/style.css
  additionalpage/game.html
Labels: gssoc23, level2

#381 [GSSOC '23]: Added all single player game in readme file (Table)
  README.md
Labels: gssoc23, level1

#385 Magic Tiles New Game Added
  SinglePlayer - Games/Magic_Tiles/MUSIC.mp3
  SinglePlayer - Games/Magic_Tiles/index.html
  SinglePlayer - Games/Magic_Tiles/script.js
Labels: gssoc23, level2

#376 Crossword game Added
  SinglePlayer - Games/Banner - image/CROSSWORD_PUZZLE_GAME.png
  SinglePlayer - Games/Crossword_Puzzle_Game/README.md
  SinglePlayer - Games/Crossword_Puzzle_Game/index.html
  SinglePlayer - Games/Crossword_Puzzle_Game/script.js
  SinglePlayer - Games/Crossword_Puzzle_Game/style.css
Labels: gssoc23, level2

#401 Added Color Blast Game
  README.md
  SinglePlayer - Games/Banner - image/Color_Blast_Game.png
  SinglePlayer - Games/Color_Blast_game/index.html
  SinglePlayer - Games/Color_Blast_game/script.js
  SinglePlayer - Games/Color_Blast_game/style.css
  additionalpage/game.html
Labels: gssoc23, level2

#402 Rabbit_Game Added
  README.md
  SinglePlayer - Games/Banner - image/Rabbit_Game.png
  SinglePlayer - Games/Rabbit_Game/Index.html
  SinglePlayer - Games/Rabbit_Game/script.js
  SinglePlayer - Games/Rabbit_Game/style.css
  additionalpage/game.html
Labels: gssoc23, level2

#406 Guess the Correct Logo game added
  README.md
  SinglePlayer - Games/Banner - image/Guess_The_Correct_Logo.png
  SinglePlayer - Games/Guess_the_Correct_Logo/README.md
  SinglePlayer - Games/Guess_the_Correct_Logo/assests/apple1.png
  SinglePlayer - Games/Guess_the_Correct_Logo/assests/apple2.png
  SinglePlayer - Games/Guess_the_Correct_Logo/assests/bmw1.png
  SinglePlayer - Games/Guess_the_Correct_Logo/assests/bmw2.png
  SinglePlayer - Games/Guess_the_Correct_Logo/assests/burgerking1.png
  SinglePlayer - Games/Guess_the_Correct_Logo/assests/burgerking2.png
  SinglePlayer - Games/Guess_the_Correct_Logo/assests/dominos1.png
  SinglePlayer - Games/Guess_the_Correct_Logo/assests/dominos2.png
  SinglePlayer - Games/Guess_the_Correct_Logo/assests/google1.png
  SinglePlayer - Games/Guess_the_Correct_Logo/assests/google2.png
  SinglePlayer - Games/Guess_the_Correct_Logo/assests/hp1.png
  SinglePlayer - Games/Guess_the_Correct_Logo/assests/hp2.png
  SinglePlayer - Games/Guess_the_Correct_Logo/assests/ibm1.png
  SinglePlayer - Games/Guess_the_Correct_Logo/assests/ibm2.png
  SinglePlayer - Games/Guess_the_Correct_Logo/assests/instagram1.png
  SinglePlayer - Games/Guess_the_Correct_Logo/assests/instagram2.png
  SinglePlayer - Games/Guess_the_Correct_Logo/assests/microsoft1.png
  SinglePlayer - Games/Guess_the_Correct_Logo/assests/microsoft2.png
  SinglePlayer - Games/Guess_the_Correct_Logo/assests/nasa1.png
  SinglePlayer - Games/Guess_the_Correct_Logo/assests/nasa2.png
  SinglePlayer - Games/Guess_the_Correct_Logo/assests/pepsi1.png
  SinglePlayer - Games/Guess_the_Correct_Logo/assests/pepsi2.png
  SinglePlayer - Games/Guess_the_Correct_Logo/assests/rolex1.png
  SinglePlayer - Games/Guess_the_Correct_Logo/assests/rolex2.png
  SinglePlayer - Games/Guess_the_Correct_Logo/assests/starbucks1.png
  SinglePlayer - Games/Guess_the_Correct_Logo/assests/starbucks2.png
  SinglePlayer - Games/Guess_the_Correct_Logo/assests/subway1.png
  SinglePlayer - Games/Guess_the_Correct_Logo/assests/subway2.png
  SinglePlayer - Games/Guess_the_Correct_Logo/assests/twitter1.png
  SinglePlayer - Games/Guess_the_Correct_Logo/assests/twitter2.png
  SinglePlayer - Games/Guess_the_Correct_Logo/game.html
  SinglePlayer - Games/Guess_the_Correct_Logo/index.html
  SinglePlayer - Games/Guess_the_Correct_Logo/main.css
  SinglePlayer - Games/Guess_the_Correct_Logo/script.js
  SinglePlayer - Games/Guess_the_Correct_Logo/style.css
  additionalpage/game.html
Labels: gssoc23, level2

#418 Added Kill_The_Bird_Game
  README.md
  SinglePlayer - Games/Banner - image/Kill_The_Bird_Game.png
  SinglePlayer - Games/Kill_The_Bird_Game/index.html
  SinglePlayer - Games/Kill_The_Bird_Game/style.css
  additionalpage/game.html
Labels: gssoc23, level2

#419 Added Carnival Target game
  NewGame.md
  SinglePlayer - Games/Banner - image/Carnival_game.png
  SinglePlayer - Games/Carnival_game/Carnival_game.png
  SinglePlayer - Games/Carnival_game/bkg.jpg
  SinglePlayer - Games/Carnival_game/carnival.html
  SinglePlayer - Games/Carnival_game/game_over.png
  SinglePlayer - Games/Carnival_game/style.css
  additionalpage/game.html
Labels: gssoc23, level2

#431 Virtual Piano
  README.md
  SinglePlayer - Games/Banner - image/Virtual_Piano.png
  SinglePlayer - Games/Virtual Piano/index.html
  SinglePlayer - Games/Virtual Piano/piano.png
  SinglePlayer - Games/Virtual Piano/script.js
  SinglePlayer - Games/Virtual Piano/style.css
  SinglePlayer - Games/Virtual Piano/tunes/;.wav
  SinglePlayer - Games/Virtual Piano/tunes/a.wav
  SinglePlayer - Games/Virtual Piano/tunes/d.wav
  SinglePlayer - Games/Virtual Piano/tunes/e.wav
  SinglePlayer - Games/Virtual Piano/tunes/f.wav
  SinglePlayer - Games/Virtual Piano/tunes/g.wav
  SinglePlayer - Games/Virtual Piano/tunes/h.wav
  SinglePlayer - Games/Virtual Piano/tunes/j.wav
  SinglePlayer - Games/Virtual Piano/tunes/k.wav
  SinglePlayer - Games/Virtual Piano/tunes/l.wav
  SinglePlayer - Games/Virtual Piano/tunes/o.wav
  SinglePlayer - Games/Virtual Piano/tunes/p.wav
  SinglePlayer - Games/Virtual Piano/tunes/s.wav
  SinglePlayer - Games/Virtual Piano/tunes/t.wav
  SinglePlayer - Games/Virtual Piano/tunes/u.wav
  SinglePlayer - Games/Virtual Piano/tunes/w.wav
  SinglePlayer - Games/Virtual Piano/tunes/y.wav
  additionalpage/game.html
Labels: gssoc23, level2

#436 Implement contact validation
  additionalpage/contact.html
  dist/main.css
  src/validation.js
Labels: gssoc23, level2

#424 Coloron game
  README.md
  SinglePlayer - Games/Coloron Game/coloron.png
  SinglePlayer - Games/Coloron Game/index.html
  SinglePlayer - Games/Coloron Game/script.js
  SinglePlayer - Games/Coloron Game/style.css
  additionalpage/game.html
Labels: gssoc23, level2

#438 Adding Pickle Rick Maze Game
  README.md
  SinglePlayer - Games/Banner - image/Pickle_Rick_Maze_Game.png
  SinglePlayer - Games/Pickle_Rick_Maze_Game/index.html
  SinglePlayer - Games/Pickle_Rick_Maze_Game/index.js
  SinglePlayer - Games/Pickle_Rick_Maze_Game/styles.css
  additionalpage/game.html
  assets/images/Pickle_Rick_Maze_Game.png
Labels: gssoc23, level2

#450 Added NewGame.md
  NewGame.md
Labels: gssoc23, level1

#458 Bad depot
  README.md
  SinglePlayer - Games/Bad_Depot/baddepot.js
  SinglePlayer - Games/Bad_Depot/baddepot.min.js
  SinglePlayer - Games/Bad_Depot/index.html
  SinglePlayer - Games/Bad_Depot/style.css
  SinglePlayer - Games/Banner - image/Bad_Depot.png
  additionalpage/game.html
Labels: gssoc23, level2

#469 Added Revealing Effect Animation In home page
  additionalpage/game.html
  index.html
Labels: gssoc23, level1

#466 Mastermind game
  README.md
  SinglePlayer - Games/Banner - image/Mastermind.png
  SinglePlayer - Games/Mastemind/FredokaOne-Regular.ttf
  SinglePlayer - Games/Mastemind/README.md
  SinglePlayer - Games/Mastemind/Screenshots/Mastermind.png
  SinglePlayer - Games/Mastemind/game.js
  SinglePlayer - Games/Mastemind/index.html
  SinglePlayer - Games/Mastemind/styles.css
  additionalpage/game.html
Labels: gssoc23, level2

#468 Whisker's leap
  README.md
  SinglePlayer - Games/Banner - image/Air_Balloon.png
  SinglePlayer - Games/Banner - image/Whisker's_Leap.png
  SinglePlayer - Games/Whisker's_Leap/ReadMe.md
  SinglePlayer - Games/Whisker's_Leap/index.html
  additionalpage/game.html
Labels: gssoc23, level2

#442 Chill_Lion_Game Added
  README.md
  SinglePlayer - Games/Banner - image/Chill_The_Lion_Game.gif
  SinglePlayer - Games/Chill_Lion_Game/index.html
  SinglePlayer - Games/Chill_Lion_Game/script.js
  SinglePlayer - Games/Chill_Lion_Game/style.css
Labels: gssoc23, level2

#476 Made contact page responsive
  dist/contact.css
Labels: gssoc23, level2

#481 Added game: RGB riddle
  README.md
  SinglePlayer - Games/Banner - image/RGB_Riddle.png
  SinglePlayer - Games/RGB_Riddle/RGB.html
  SinglePlayer - Games/RGB_Riddle/ReadMe.md
  SinglePlayer - Games/RGB_Riddle/script.js
  SinglePlayer - Games/RGB_Riddle/styles.css
  additionalpage/game.html
Labels: gssoc23, level2

#487 New game is added
  README.md
  SinglePlayer - Games/Among_Us_Game/assets/audio/Killing_Sound.mp3
  SinglePlayer - Games/Among_Us_Game/assets/audio/Sound.mp3
  SinglePlayer - Games/Among_Us_Game/assets/images/Amogus_Icon.png
  SinglePlayer - Games/Among_Us_Game/assets/images/Crewmate_killed.png
  SinglePlayer - Games/Among_Us_Game/assets/images/Crewmate_normal.png
  SinglePlayer - Games/Among_Us_Game/assets/images/Impostor_Killing.png
  SinglePlayer - Games/Among_Us_Game/assets/images/Impostor_normalWalk.png
  SinglePlayer - Games/Among_Us_Game/assets/images/Killing_Animation.png
  SinglePlayer - Games/Among_Us_Game/assets/images/Loading_Screen.jpg
  SinglePlayer - Games/Among_Us_Game/assets/images/The_Skeld_Cafeteria.png
  SinglePlayer - Games/Among_Us_Game/assets/images/kill_button.png
  SinglePlayer - Games/Among_Us_Game/index.html
  SinglePlayer - Games/Among_Us_Game/script.js
  SinglePlayer - Games/Among_Us_Game/style.css
  additionalpage/game.html
Labels: gssoc23, level2

#510 Adding Falling Blocks Game
  README.md
  SinglePlayer - Games/Banner - image/FallingBlocks.png
  SinglePlayer - Games/Falling Blocks/README.md
  SinglePlayer - Games/Falling Blocks/index.html
  SinglePlayer - Games/Falling Blocks/script.js
  SinglePlayer - Games/Falling Blocks/style.css
  additionalpage/game.html
Labels: gssoc23, level2, Change request

#520 Mix And Paint
  README.md
  SinglePlayer - Games/Banner - image/MixAndPaint.png
  SinglePlayer - Games/MixAndPaint/MixAndPaint.png
  SinglePlayer - Games/MixAndPaint/images/alien.png
  SinglePlayer - Games/MixAndPaint/images/amongus.png
  SinglePlayer - Games/MixAndPaint/images/bear.png
  SinglePlayer - Games/MixAndPaint/images/cactus.png
  SinglePlayer - Games/MixAndPaint/images/cap.png
  SinglePlayer - Games/MixAndPaint/images/car.png
  SinglePlayer - Games/MixAndPaint/images/cocacola.png
  SinglePlayer - Games/MixAndPaint/images/cucumber.png
  SinglePlayer - Games/MixAndPaint/images/flower.png
  SinglePlayer - Games/MixAndPaint/images/gloss.png
  SinglePlayer - Games/MixAndPaint/images/harrystyles.png
  SinglePlayer - Games/MixAndPaint/images/icecream.png
  SinglePlayer - Games/MixAndPaint/images/lightbolt.png
  SinglePlayer - Games/MixAndPaint/images/lolipop.png
  SinglePlayer - Games/MixAndPaint/images/macd.png
  SinglePlayer - Games/MixAndPaint/images/milk.png
  SinglePlayer - Games/MixAndPaint/images/saturn.png
  SinglePlayer - Games/MixAndPaint/images/shoes.png
  SinglePlayer - Games/MixAndPaint/images/smily.png
  SinglePlayer - Games/MixAndPaint/images/sweater.png
  SinglePlayer - Games/MixAndPaint/images/unocard.png
  SinglePlayer - Games/MixAndPaint/index.html
  SinglePlayer - Games/MixAndPaint/script.js
  SinglePlayer - Games/MixAndPaint/style.css
  additionalpage/game.html
Labels: gssoc23, level2

#521 changes-made-to-navbar
  dist/main.css
Labels: gssoc23, level1

#529 Added Color Blast Game
  README.md
  SinglePlayer - Games/Banner - image/Bubble Blast Game.png
  SinglePlayer - Games/Bubble_Blast_Game/assets/Bubble_Blast_Game.png
  SinglePlayer - Games/Bubble_Blast_Game/assets/bubble-sprites.png
  SinglePlayer - Games/Bubble_Blast_Game/assets/bubble1.png
  SinglePlayer - Games/Bubble_Blast_Game/assets/bubble2.png
  SinglePlayer - Games/Bubble_Blast_Game/index.html
  SinglePlayer - Games/Bubble_Blast_Game/script.js
  SinglePlayer - Games/Bubble_Blast_Game/start.html
  SinglePlayer - Games/Bubble_Blast_Game/style.css
  additionalpage/game.html
Labels: gssoc23, level1

#526 Stack em up - GSSOC'23
  README.md
  SinglePlayer - Games/Banner - image/Stack_Em_Up.png
  SinglePlayer - Games/Stack_Em_Up/README.md
  SinglePlayer - Games/Stack_Em_Up/Screenshots/Stack_Em_Up.png
  SinglePlayer - Games/Stack_Em_Up/game.js
  SinglePlayer - Games/Stack_Em_Up/index.html
  SinglePlayer - Games/Stack_Em_Up/styles.css
  additionalpage/game.html
Labels: gssoc23, level1

#531 Added New counter cards
  counter.css
  index.html
Labels: gssoc23, level1

#518 Added Hunt_Your_Card
  README.md
  SinglePlayer - Games/Banner - image/Hunt_your_card.png
  SinglePlayer - Games/Hunt_Your_Card/README.md
  SinglePlayer - Games/Hunt_Your_Card/images/AceSpades.png
  SinglePlayer - Games/Hunt_Your_Card/images/card-AceSpades.png
  SinglePlayer - Games/Hunt_Your_Card/images/card-JackClubs.png
  SinglePlayer - Games/Hunt_Your_Card/images/card-KingHearts.png
  SinglePlayer - Games/Hunt_Your_Card/images/card-QueenDiamonds.png
  SinglePlayer - Games/Hunt_Your_Card/images/card-back-Blue.png
  SinglePlayer - Games/Hunt_Your_Card/index.html
  SinglePlayer - Games/Hunt_Your_Card/script.js
  SinglePlayer - Games/Hunt_Your_Card/style.css
  additionalpage/game.html
Labels: gssoc23, level2, Change request

#540 commit msg #403
  SinglePlayer - Games/Banner - image/Guess_a_word.png
  SinglePlayer - Games/Guess_a_Word/index.html
  SinglePlayer - Games/Guess_a_Word/styles.css
  additionalpage/game.html
Labels: gssoc23, level1

#547 Added Cable_Maze Game
  README.md
  SinglePlayer - Games/Banner - image/Cable_Maze.png
  SinglePlayer - Games/Cable_Maze/README.md
  SinglePlayer - Games/Cable_Maze/index.html
  SinglePlayer - Games/Cable_Maze/main.js
  additionalpage/game.html
Labels: gssoc23, level1

#551 Crossy_Road_Game Added
  README.md
  SinglePlayer - Games/Banner - image/Crossy_Road_Game.gif
  SinglePlayer - Games/Crossy_Road_Game/README.md
  SinglePlayer - Games/Crossy_Road_Game/index.html
  SinglePlayer - Games/Crossy_Road_Game/script.js
  SinglePlayer - Games/Crossy_Road_Game/style.css
  additionalpage/game.html
Labels: gssoc23, level1

#546 [GSSoC'23] Guess The Random Shape Game Completed
  README.md
  SinglePlayer - Games/Banner - image/Guess_The_Random_Shape.png
  SinglePlayer - Games/Guess_The_Random_Shape/README.md
  SinglePlayer - Games/Guess_The_Random_Shape/favicon.ico
  SinglePlayer - Games/Guess_The_Random_Shape/index.html
  SinglePlayer - Games/Guess_The_Random_Shape/script.js
  SinglePlayer - Games/Guess_The_Random_Shape/style.css
  additionalpage/game.html
Labels: gssoc23, level1

#567 added share button
  additionalpage/game.html
  src/share.js
  style.css
Labels: gssoc23, level2

#555 New game added and fixes bug
  README.md
  SinglePlayer - Games/Banner - image/Bounce.png
  SinglePlayer - Games/Bounce/.htaccess
  SinglePlayer - Games/Bounce/AStar.js
  SinglePlayer - Games/Bounce/KeyCode.js
  SinglePlayer - Games/Bounce/List.js
  SinglePlayer - Games/Bounce/Queue.js
  SinglePlayer - Games/Bounce/Sounds.js
  SinglePlayer - Games/Bounce/Storage.js
  SinglePlayer - Games/Bounce/Utils.js
  SinglePlayer - Games/Bounce/audio/bounce.mp3
  SinglePlayer - Games/Bounce/audio/brick.mp3
  SinglePlayer - Games/Bounce/audio/end.mp3
  SinglePlayer - Games/Bounce/cache.manifest
  SinglePlayer - Games/Bounce/design/style.css
  SinglePlayer - Games/Bounce/fonts/glsnecb.ttf
  SinglePlayer - Games/Bounce/index.html
  SinglePlayer - Games/Bounce/source/Ball.js
  SinglePlayer - Games/Bounce/source/Board.js
  SinglePlayer - Games/Bounce/source/Brick.js
  SinglePlayer - Games/Bounce/source/Bricks.js
  SinglePlayer - Games/Bounce/source/Display.js
  SinglePlayer - Games/Bounce/source/HighScores.js
  SinglePlayer - Games/Bounce/source/Keyboard.js
  SinglePlayer - Games/Bounce/source/Main.js
  SinglePlayer - Games/Bounce/source/Mode.js
  SinglePlayer - Games/Bounce/source/Score.js
  SinglePlayer - Games/Bounce/source/Ship.js
  SinglePlayer - Games/Bounce/source/Tail.js
  SinglePlayer - Games/Bounce/style.css
  additionalpage/game.html
Labels: gssoc23, level2

#552 Update README.md
  README.md
Labels: gssoc23, level1

#549 Spelling Bee (New Game)
  SinglePlayer - Games/Banner - image/SpellinBee.png
  SinglePlayer - Games/SpellingBee/SpellinBee.png
  SinglePlayer - Games/SpellingBee/index.html
  additionalpage/game.html
Labels: gssoc23, level1

#579 Readme updates for adding share button
  NewGame.md
Labels: gssoc23, level1

#511 AngryBoars game is added
  README.md
  SinglePlayer - Games/AngryBoars/README.md
  SinglePlayer - Games/AngryBoars/cat.mp3
  SinglePlayer - Games/AngryBoars/game.html
  SinglePlayer - Games/AngryBoars/index.html
  SinglePlayer - Games/AngryBoars/script.js
  SinglePlayer - Games/AngryBoars/sprite.png
  additionalpage/game.html
Labels: gssoc23, level2

#578 Frogger game added - GSSOC'23
  README.md
  SinglePlayer - Games/Banner - image/Frogger.png
  SinglePlayer - Games/Frogger/README.md
  SinglePlayer - Games/Frogger/Screenshots/Frogger.png
  SinglePlayer - Games/Frogger/assets/collision.wav
  SinglePlayer - Games/Frogger/assets/move.wav
  SinglePlayer - Games/Frogger/assets/winner.wav
  SinglePlayer - Games/Frogger/index.html
  SinglePlayer - Games/Frogger/script.js
  SinglePlayer - Games/Frogger/style.css
  additionalpage/game.html
Labels: gssoc23, level1

#588 Converted images to URL
  MultiPlayer - Games/Ludo_4_Player/index.html
  SinglePlayer - Games/1024_moves_games/index.html
  SinglePlayer - Games/1024_moves_games/style.js
  SinglePlayer - Games/3d_car_racing_game/script.js
  SinglePlayer - Games/Among_Us_Game/index.html
  SinglePlayer - Games/Among_Us_Game/script.js
  SinglePlayer - Games/AngryBoars/game.html
  SinglePlayer - Games/Anthority/game/css/style.css
  SinglePlayer - Games/Anti Virus/Glitch/src/allinone.js
  SinglePlayer - Games/Anti Virus/Glitch/src/boot.js
  SinglePlayer - Games/ArmorAlley/css/aa.css
  SinglePlayer - Games/ArmorAlley/index.html
  SinglePlayer - Games/Black_Jack/index.html
  SinglePlayer - Games/Bubble_Blast_Game/start.html
  SinglePlayer - Games/Candy_Crush/script.js
  SinglePlayer - Games/Card flip Game/index.html
  SinglePlayer - Games/DEEP SPACE/src/css/app.css
  SinglePlayer - Games/DEEP SPACE/src/scss/app.scss
  SinglePlayer - Games/Doremon_Puzzle/index.html
  SinglePlayer - Games/Dragon_World_Game/style.css
  SinglePlayer - Games/Drum_Kit_Play_Game/styles.css
  SinglePlayer - Games/Guess_the_Correct_Logo/script.js
  SinglePlayer - Games/HexGL-master/css/multi.css
  SinglePlayer - Games/Hunt_Your_Card/index.html
  SinglePlayer - Games/Hunt_Your_Card/script.js
  SinglePlayer - Games/Jumbit/src/index.html
  SinglePlayer - Games/MixAndPaint/script.js
  SinglePlayer - Games/Pinball/index.html
  SinglePlayer - Games/Spaceship Escort/index.html
  SinglePlayer - Games/SpellingBee/index.html
  SinglePlayer - Games/StarshipPanic/css/main.css
  SinglePlayer - Games/StarshipPanic/index.html
  SinglePlayer - Games/StarshipPanic/js/main.js
  SinglePlayer - Games/Virtual Piano/style.css
  SinglePlayer - Games/Whake_M_Mole_Game/mole.css
  SinglePlayer - Games/Whake_M_Mole_Game/mole.js
  SinglePlayer - Games/alien-shooting-game/index.html
  SinglePlayer - Games/back-up-master/src/beam.js
  SinglePlayer - Games/back-up-master/src/core.js
  SinglePlayer - Games/back-up-master/src/game.js
  SinglePlayer - Games/back-up-master/src/hud.js
  SinglePlayer - Games/back-up-master/src/menu.js
  SinglePlayer - Games/back-up-master/src/platform.js
  SinglePlayer - Games/back-up-master/src/player.js
  SinglePlayer - Games/back-up-master/src/wall.js
  SinglePlayer - Games/black_ jack_game/black-jack-master/index.html
  SinglePlayer - Games/doodle-jump-game/index.js
  SinglePlayer - Games/doodle-jump-game/styles.css
  SinglePlayer - Games/floppybird/css/main.css
  SinglePlayer - Games/floppybird/index.html
  SinglePlayer - Games/pig game/index.html
  SinglePlayer - Games/slide-puzzle-master/index.html
  SinglePlayer - Games/space-invaders/space-invaders-master/space.js
  SinglePlayer - Games/tower/index.html
  additionalpage/contact.html
  additionalpage/game.html
  dist/main.css
  index.html
  landing-page/index.html
  src/main.css
Labels: gssoc23, level3

#587 Guess the flag
  MultiPlayer - Games/Guess_Flag/README.md
  MultiPlayer - Games/Guess_Flag/index.html
  MultiPlayer - Games/Guess_Flag/preview.png
  MultiPlayer - Games/Guess_Flag/script.js
  MultiPlayer - Games/Guess_Flag/style.css
  additionalpage/multiplayer.html
Labels: gssoc23, level1

#584 Lonely_Phantom game added by Aryan5464
  README.md
  SinglePlayer - Games/Banner - image/Lonely Phantom.png
  SinglePlayer - Games/Lonely_Phantom/README.md
  SinglePlayer - Games/Lonely_Phantom/index.html
  additionalpage/game.html
Labels: gssoc23, level1

#583 Added Lights out
  README.md
  SinglePlayer - Games/Banner - image/Lights_Out.png
  SinglePlayer - Games/Lights_Out/ReadMe.md
  SinglePlayer - Games/Lights_Out/index.html
  SinglePlayer - Games/Lights_Out/script.js
  SinglePlayer - Games/Lights_Out/style.css
  additionalpage/game.html
Labels: gssoc23, level1

#580 Enhance styling of navigation text ⚡
  dist/main.css
  index.html
Labels: gssoc23, level1

#597 random cards are shown for wrong prompts
  src/script.js
Labels: gssoc23, level1

#616 Added New Slider In Home Page
  dist/sidebar.css
  index.html
Labels: gssoc23, level2

#606 added Preloader
  .DS_Store
  assets/preloader.gif
  counter.css
  index.html
Labels: gssoc23, level1

#611 Docker
  Dockerfile
Labels: gssoc23, level1

#622 Flying Block game is added
  README.md
  SinglePlayer - Games/TheFlyingBlock/FlyingBlock.png
  SinglePlayer - Games/TheFlyingBlock/game.html
  SinglePlayer - Games/TheFlyingBlock/index.html
  SinglePlayer - Games/TheFlyingBlock/info.html
  additionalpage/game.html
Labels: gssoc23, level1

#619 Escape Room added 👍
  README.md
  SinglePlayer - Games/Banner - image/Escape_Room.png
  SinglePlayer - Games/Escape_Room/index.html
  SinglePlayer - Games/Escape_Room/script.js
  SinglePlayer - Games/Escape_Room/style.css
  additionalpage/game.html
Labels: gssoc23, level1

#627 simon says game
  README.md
  SinglePlayer - Games/Banner - image/simon-says.png
  SinglePlayer - Games/simon-says/README.md
  SinglePlayer - Games/simon-says/index.html
  SinglePlayer - Games/simon-says/script.js
  SinglePlayer - Games/simon-says/sounds/1.mp3
  SinglePlayer - Games/simon-says/sounds/2.mp3
  SinglePlayer - Games/simon-says/sounds/3.mp3
  SinglePlayer - Games/simon-says/sounds/4.mp3
  SinglePlayer - Games/simon-says/sounds/error.wav
  SinglePlayer - Games/simon-says/styles.css
  additionalpage/game.html
Labels: gssoc23, level1

#633 Slingshot_Game Added
  README.md
  SinglePlayer - Games/Banner - image/Slingshot_Game.gif
  SinglePlayer - Games/Slingshot_Game/README.md
  SinglePlayer - Games/Slingshot_Game/index.html
  SinglePlayer - Games/Slingshot_Game/script.js
  SinglePlayer - Games/Slingshot_Game/style.css
  additionalpage/game.html
Labels: gssoc23, level2

#635 Rabbit_And_Fox_Game
  README.md
  SinglePlayer - Games/Banner - image/Rabbit_And_Fox .gif
  SinglePlayer - Games/Rabbit_And_Fox_Game/README.md
  SinglePlayer - Games/Rabbit_And_Fox_Game/index.html
  SinglePlayer - Games/Rabbit_And_Fox_Game/script.js
  SinglePlayer - Games/Rabbit_And_Fox_Game/style.css
  additionalpage/game.html
Labels: gssoc23, level1

#625 Anime clicker game is added
  README.md
  SinglePlayer - Games/Anime-Clicker/app.html
  SinglePlayer - Games/Anime-Clicker/estilo.css
  SinglePlayer - Games/Anime-Clicker/fim_de_jogo.html
  SinglePlayer - Games/Anime-Clicker/img/bg.jpg
  SinglePlayer - Games/Anime-Clicker/img/coracao_cheio.png
  SinglePlayer - Games/Anime-Clicker/img/coracao_vazio.png
  SinglePlayer - Games/Anime-Clicker/img/game.png
  SinglePlayer - Games/Anime-Clicker/img/game_over.png
  SinglePlayer - Games/Anime-Clicker/img/mata_mosquito.png
  SinglePlayer - Games/Anime-Clicker/img/mosca.png
  SinglePlayer - Games/Anime-Clicker/index.html
  SinglePlayer - Games/Anime-Clicker/jogo.js
  SinglePlayer - Games/Anime-Clicker/mosquito.png
  SinglePlayer - Games/Anime-Clicker/vitoria.html
  additionalpage/game.html
Labels: gssoc23, level1

#665 API Added & GPT ChatBot Fixed
  chatBot/script.js
  chatBot/style.css
Labels: gssoc23, level1

#663 Added Astray
  README.md
  SinglePlayer - Games/Astray/Box2dWeb.min.js
  SinglePlayer - Games/Astray/README.md
  SinglePlayer - Games/Astray/Three.js
  SinglePlayer - Games/Astray/ball.png
  SinglePlayer - Games/Astray/brick.png
  SinglePlayer - Games/Astray/concrete.png
  SinglePlayer - Games/Astray/index.html
  SinglePlayer - Games/Astray/keyboard.js
  SinglePlayer - Games/Astray/maze.js
  assets/images/Astray.png
Labels: gssoc23, level1

#671 [New Game] : AI Chess Added
  MultiPlayer - Games/AI-Chess/.DS_Store
  MultiPlayer - Games/AI-Chess/README.md
  MultiPlayer - Games/AI-Chess/css/main.css
  MultiPlayer - Games/AI-Chess/img/chesspieces/wikipedia/bB.png
  MultiPlayer - Games/AI-Chess/img/chesspieces/wikipedia/bK.png
  MultiPlayer - Games/AI-Chess/img/chesspieces/wikipedia/bN.png
  MultiPlayer - Games/AI-Chess/img/chesspieces/wikipedia/bP.png
  MultiPlayer - Games/AI-Chess/img/chesspieces/wikipedia/bQ.png
  MultiPlayer - Games/AI-Chess/img/chesspieces/wikipedia/bR.png
  MultiPlayer - Games/AI-Chess/img/chesspieces/wikipedia/wB.png
  MultiPlayer - Games/AI-Chess/img/chesspieces/wikipedia/wK.png
  MultiPlayer - Games/AI-Chess/img/chesspieces/wikipedia/wN.png
  MultiPlayer - Games/AI-Chess/img/chesspieces/wikipedia/wP.png
  MultiPlayer - Games/AI-Chess/img/chesspieces/wikipedia/wQ.png
  MultiPlayer - Games/AI-Chess/img/chesspieces/wikipedia/wR.png
  MultiPlayer - Games/AI-Chess/index.html
  MultiPlayer - Games/AI-Chess/js/chess.js
  MultiPlayer - Games/AI-Chess/js/main.js
  README.md
Labels: gssoc23, level1

#674 Fixed Overflow issue in README.md
  README.md
Labels: gssoc23, level1
