Repository ChromeGaming/GameSphere, pull requests merged in 2024-05, with the labels that each got.

#944 Fixed #942 theme selector successfully aligned with navbar
  dist/color-theme.css
Labels: bug, gssoc, level2, Approved

#974 logo added in navbar
  index.html
Labels: gssoc, level2, Approved

#980 Hand_Cricket_Champ
  README.md
  SinglePlayer - Games/Banner - image/Hand_Cricket_Champ.png
  SinglePlayer - Games/Hand_Cricket_Champ/images/fistL.png
  SinglePlayer - Games/Hand_Cricket_Champ/images/fistR.png
  SinglePlayer - Games/Hand_Cricket_Champ/images/fiveL.png
  SinglePlayer - Games/Hand_Cricket_Champ/images/fiveR.png
  SinglePlayer - Games/Hand_Cricket_Champ/images/fourL.png
  SinglePlayer - Games/Hand_Cricket_Champ/images/fourR.png
  SinglePlayer - Games/Hand_Cricket_Champ/images/oneL.png
  SinglePlayer - Games/Hand_Cricket_Champ/images/oneR.png
  SinglePlayer - Games/Hand_Cricket_Champ/images/sixL.png
  SinglePlayer - Games/Hand_Cricket_Champ/images/sixR.png
  SinglePlayer - Games/Hand_Cricket_Champ/images/threeL.png
  SinglePlayer - Games/Hand_Cricket_Champ/images/threeR.png
  SinglePlayer - Games/Hand_Cricket_Champ/images/twoL.png
  SinglePlayer - Games/Hand_Cricket_Champ/images/twoR.png
  SinglePlayer - Games/Hand_Cricket_Champ/index.html
  SinglePlayer - Games/Hand_Cricket_Champ/script.js
  SinglePlayer - Games/Hand_Cricket_Champ/style.css
  additionalpage/game.html
Labels: 🎮 new game, gssoc, level2, Approved

#977 rock-paper-scissors game added
  SinglePlayer - Games/rock-paper-scissor/paper.png
  SinglePlayer - Games/rock-paper-scissor/rock.png
  SinglePlayer - Games/rock-paper-scissor/rps.css
  SinglePlayer - Games/rock-paper-scissor/rps.html
  SinglePlayer - Games/rock-paper-scissor/rps.js
  SinglePlayer - Games/rock-paper-scissor/scissors.png
  additionalpage/game.html
  assets/images/people-playing-paper-rock-scissors-royalty-free-illustration-1583269312.jpg
Labels: 🎮 new game, gssoc, level2, Approved

#931 Added GSSoC image
  README.md
Labels: gssoc, level1, Approved

#941 Added icons on the navbar
  index.html
Labels: gssoc, level1, Approved

#949 Pop My Balloon game added
  MultiPlayer - Games/Pop_My_Balloon/BalloonAnimation.css
  MultiPlayer - Games/Pop_My_Balloon/BalloonText.html
  MultiPlayer - Games/Pop_My_Balloon/README.md
  MultiPlayer - Games/Pop_My_Balloon/index.html
  MultiPlayer - Games/Pop_My_Balloon/script.js
  MultiPlayer - Games/Pop_My_Balloon/styles.css
  README.md
  additionalpage/multiplayer.html
  assets/images/Pop_My_Balloon.png
Labels: 🎮 new game, gssoc, level2, Approved

#950 Fixed Newsletter Form. Issue #935
  index.html
Labels: bug, gssoc, level1, Approved

#952 Hover Issue in Top Pouplar Game #927
  index.html
  style.css
Labels: bug, gssoc, level1, Approved

#953 Hangman Game done
  SinglePlayer - Games/Hangman Game play/Hangman Game/README.md
  SinglePlayer - Games/Hangman Game play/Hangman Game/images/hangman-0.svg
  SinglePlayer - Games/Hangman Game play/Hangman Game/images/hangman-1.svg
  SinglePlayer - Games/Hangman Game play/Hangman Game/images/hangman-2.svg
  SinglePlayer - Games/Hangman Game play/Hangman Game/images/hangman-3.svg
  SinglePlayer - Games/Hangman Game play/Hangman Game/images/hangman-4.svg
  SinglePlayer - Games/Hangman Game play/Hangman Game/images/hangman-5.svg
  SinglePlayer - Games/Hangman Game play/Hangman Game/images/hangman-6.svg
  SinglePlayer - Games/Hangman Game play/Hangman Game/images/lost.gif
  SinglePlayer - Games/Hangman Game play/Hangman Game/images/victory.gif
  SinglePlayer - Games/Hangman Game play/Hangman Game/index.html
  SinglePlayer - Games/Hangman Game play/Hangman Game/screenshot.webp
  SinglePlayer - Games/Hangman Game play/Hangman Game/script.js
  SinglePlayer - Games/Hangman Game play/Hangman Game/style.css
  SinglePlayer - Games/Hangman Game play/Hangman Game/word-list.js
Labels: 🎮 new game, gssoc, level1, Approved

#955 SIMON_GAME is Added
  README.md
  SinglePlayer - Games/Banner - image/SIMON_GAME.png
  SinglePlayer - Games/SIMON_GAME/game.js
  SinglePlayer - Games/SIMON_GAME/index.html
  SinglePlayer - Games/SIMON_GAME/sounds/blue.mp3
  SinglePlayer - Games/SIMON_GAME/sounds/green.mp3
  SinglePlayer - Games/SIMON_GAME/sounds/red.mp3
  SinglePlayer - Games/SIMON_GAME/sounds/wrong.mp3
  SinglePlayer - Games/SIMON_GAME/sounds/yellow.mp3
  SinglePlayer - Games/SIMON_GAME/styles.css
  additionalpage/game.html
Labels: 🎮 new game, gssoc, level1, Approved

#956 Cubula_Game is added
  README.md
  SinglePlayer - Games/Banner - image/Cubula_Game.png
  SinglePlayer - Games/Cubula_Game/cubula0.gif
  SinglePlayer - Games/Cubula_Game/cubula1.gif
  SinglePlayer - Games/Cubula_Game/cubula2.gif
  SinglePlayer - Games/Cubula_Game/cubula3.gif
  SinglePlayer - Games/Cubula_Game/cubula4.gif
  SinglePlayer - Games/Cubula_Game/index.html
  SinglePlayer - Games/Cubula_Game/index.js
  additionalpage/game.html
Labels: 🎮 new game, gssoc, level1, Approved

#961 added redirection link
  additionalpage/contact.html
  index.html
Labels: bug, gssoc, level1, Approved

#978 contact page enhanced
  additionalpage/contact.html
  dist/contact.css
Labels: enhancement, gssoc, level1, Approved

#979 Fixed issue #954
  index.html
Labels: bug, documentation, gssoc, level1

#994 Positioned the text properly and added the score functionality.
  SinglePlayer - Games/simon-says/script.js
  SinglePlayer - Games/simon-says/styles.css
Labels: gssoc, level2

#997 Solved issue #996- Word Guessing Game
  SinglePlayer - Games/word_guessing_game/index.html
  SinglePlayer - Games/word_guessing_game/script.js
  SinglePlayer - Games/word_guessing_game/styles.css
Labels: gssoc, level2, Approved

#999 Added Contact Links
  additionalpage/contact.html
  dist/contact.css
Labels: Assigned, level2, Approved

#987 Fixes #964: General Knowledge Quiz
  SinglePlayer - Games/General Knowledge Quiz/bg.jpg
  SinglePlayer - Games/General Knowledge Quiz/index.html
  SinglePlayer - Games/General Knowledge Quiz/js/questions.js
  SinglePlayer - Games/General Knowledge Quiz/js/script.js
  SinglePlayer - Games/General Knowledge Quiz/style.css
  additionalpage/game.html
  assets/images/GKQuiz.png
Labels: 🎮 new game, gssoc, level2

#1006 Create Readme.md
  SinglePlayer - Games/Angry Birds/Readme.md
Labels: documentation, gssoc, level1

#1016 Fix year in footer from 2023 to 2024
  index.html
Labels: gssoc, level1

#1023 Guess the sequence Game added
  README.md
  SinglePlayer - Games/Banner - image/guessthesequence.png
  SinglePlayer - Games/Guess The Sequence/index.html
  SinglePlayer - Games/Guess The Sequence/script.js
  SinglePlayer - Games/Guess The Sequence/styles.css
  additionalpage/game.html
Labels: 🎮 new game, gssoc, level2
