Repository ChromeGaming/GameSphere, pull requests merged in 2024-06, with the labels that each got.

#959 Ball_Shooting_Game
  README.md
  SinglePlayer - Games/Ball_Shooting_Game/index.html
  SinglePlayer - Games/Ball_Shooting_Game/script.js
  SinglePlayer - Games/Ball_Shooting_Game/styles.css
  SinglePlayer - Games/Banner - image/Ball_Shooting_Game.png
  additionalpage/game.html
Labels: 🎮 new game, gssoc, level2, Approved

#986 Fixes #965: Flappy Bird
  SinglePlayer - Games/Flappy_Bird_Game/images/Bird-I.png
  SinglePlayer - Games/Flappy_Bird_Game/images/Bird-II.png
  SinglePlayer - Games/Flappy_Bird_Game/images/background-img.png
  SinglePlayer - Games/Flappy_Bird_Game/index.html
  SinglePlayer - Games/Flappy_Bird_Game/script.js
  SinglePlayer - Games/Flappy_Bird_Game/style.css
  additionalpage/game.html
  assets/images/flappy.png
Labels: gssoc, level2

#1002 [Game]: Touch-No-Fire
  README.md
  SinglePlayer - Games/Touch-No-Fire-Game/Readme.md
  SinglePlayer - Games/Touch-No-Fire-Game/index.html
  SinglePlayer - Games/Touch-No-Fire-Game/script.js
  SinglePlayer - Games/Touch-No-Fire-Game/style.css
Labels: gssoc, level2

#973 Basketball is added
  README.md
  SinglePlayer - Games/Banner - image/Baseball_Game.png
  SinglePlayer - Games/Baseball_Game/README.md
  SinglePlayer - Games/Baseball_Game/assets/batter.jpeg
  SinglePlayer - Games/Baseball_Game/assets/pitcher.jpeg
  SinglePlayer - Games/Baseball_Game/extra.js
  SinglePlayer - Games/Baseball_Game/index.html
  SinglePlayer - Games/Baseball_Game/script.js
  SinglePlayer - Games/Baseball_Game/style.css
  additionalpage/game.html
Labels: gssoc, level2

#1015 Flames Game has been created.
  MultiPlayer - Games/Flames_Game/Banner-image/bg.webp
  MultiPlayer - Games/Flames_Game/index.html
  MultiPlayer - Games/Flames_Game/script.js
  MultiPlayer - Games/Flames_Game/style.css
  README.md
  additionalpage/multiplayer.html
  assets/images/Flames-Game.png
Labels: 🎮 new game, gssoc, level2

#1028 Removed additional scroll bar on console image hover
  style.css
Labels: gssoc, Easy, level1
